/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.eusubsidycompliancefrontend.models

import play.api.libs.json.{Format, Json}
import play.api.mvc.{PathBindable, QueryStringBindable}
import shapeless.tag.@@

import scala.util.Try

package object types extends SimpleJson {

  val MaxInputValue = 99999999999.99

  type IndustrySectorLimit = BigDecimal @@ IndustrySectorLimit.Tag
  object IndustrySectorLimit extends ValidatedType[BigDecimal] {
    override def validateAndTransform(in: BigDecimal): Option[BigDecimal] =
      Some(in).filter { x =>
        (x <= MaxInputValue) && (x.scale <= 2)
      }
  }

  type PositiveSubsidyAmount = BigDecimal @@ PositiveSubsidyAmount.Tag
  object PositiveSubsidyAmount extends ValidatedType[BigDecimal] {
    override def validateAndTransform(in: BigDecimal): Option[BigDecimal] =
      Some(in).filter { x =>
        (x >= 0) && (x <= MaxInputValue) && (x.scale <= 2)
      }
  }

  type SubsidyAmount = BigDecimal @@ SubsidyAmount.Tag
  object SubsidyAmount extends ValidatedType[BigDecimal] {
    override def validateAndTransform(in: BigDecimal): Option[BigDecimal] =
      Some(in).filter { x =>
        (x >= -MaxInputValue) && (x <= MaxInputValue) && (x.scale <= 2)
      }
    val Zero: SubsidyAmount = SubsidyAmount(BigDecimal(0))
  }

  type DeclarationID = String @@ DeclarationID.Tag
  object DeclarationID
      extends RegexValidatedString(
        regex = """.{1,18}"""
      )

  type TaxType = String @@ TaxType.Tag
  object TaxType
      extends RegexValidatedString(
        regex = """.{0,3}"""
      )

  type TraderRef = String @@ TraderRef.Tag
  object TraderRef
      extends RegexValidatedString(
        regex = """[A-Za-z0-9\W_ ]{1,400}""" //dev agreed setting an arbitary limit of 400
      )

  type UndertakingName = String @@ UndertakingName.Tag
  object UndertakingName
      extends RegexValidatedString(
        regex = """.{1,105}"""
      )

  type EORI = String @@ EORI.Tag
  object EORI
      extends RegexValidatedString(
        """^(gb|Gb|gB|GB|XI)[0-9]{12,15}$"""
      ) {

    val ValidLengthsWithPrefix = Set(14, 17) // Valid lengths with 2 letter prefix

    def withGbPrefix(eori: String): String =
      if (eori.startsWith("GB")) eori
      else s"GB$eori"

    def formatEori(eori: String): String = {
      val s = eori.replaceAll(" ", "")
      s.take(2).toUpperCase + s.drop(2)
    }
  }

  type UndertakingRef = String @@ UndertakingRef.Tag
  object UndertakingRef
      extends RegexValidatedString(
        regex = """[A-Za-z0-9]{1,17}""" // n.b. no longer exact match for spec which accepts n of any char
      )

  object Sector extends Enumeration {
    type Sector = Value
    val other: types.Sector.Value = Value("0")
    val transport: types.Sector.Value = Value("1")
    val agriculture: types.Sector.Value = Value("2")
    val aquaculture: types.Sector.Value = Value("3")
    val generalTrade: types.Sector.Value = Value("00")

    val otherGeneralTrade: types.Sector.Value = Value("INT00")
    val manuGroup1: types.Sector.Value = Value("INT01")
    val manuGroup2: types.Sector.Value = Value("INT02")
    val manuGroup3: types.Sector.Value = Value("INT03")
    val manuGroup4: types.Sector.Value = Value("INT04")
    val manuGroup5: types.Sector.Value = Value("INT05")
    val manuGroup6: types.Sector.Value = Value("INT06")
    val manuGroup7: types.Sector.Value = Value("INT07")

    val agricultureForestryFishing: types.Sector.Value = Value("A")
    val cropAnimalProduction: types.Sector.Value = Value("01")
    val growingNonPerennialCrops: types.Sector.Value = Value("01.1")
    val cerealsLeguminousCrops: types.Sector.Value = Value("01.11")
    val fibreCrops: types.Sector.Value = Value("01.16")
    val rice: types.Sector.Value = Value("01.12")
    val sugarCane: types.Sector.Value = Value("01.14")
    val tobacco: types.Sector.Value = Value("01.15")
    val vegetables: types.Sector.Value = Value("01.13")
    val otherNonPerennialCrops: types.Sector.Value = Value("01.19")
    val growingPerennialCrops: types.Sector.Value = Value("01.2")
    val beverageCrops: types.Sector.Value = Value("01.27")
    val citrusFruits: types.Sector.Value = Value("01.23")
    val grapes: types.Sector.Value = Value("01.21")
    val oleaginousFruits: types.Sector.Value = Value("01.26")
    val stoneFruits: types.Sector.Value = Value("01.24")
    val spicesPharmaceuticalCrops: types.Sector.Value = Value("01.28")
    val tropicalFruits: types.Sector.Value = Value("01.22")
    val otherTree: types.Sector.Value = Value("01.25")
    val otherPerennialCrops: types.Sector.Value = Value("01.29")
    val plantPropagation: types.Sector.Value = Value("01.3")
    val plantPropagation4: types.Sector.Value = Value("01.30")
    val animalProduction: types.Sector.Value = Value("01.4")
    val dairyCattle: types.Sector.Value = Value("01.41")
    val otherCattle: types.Sector.Value = Value("01.42")
    val camels: types.Sector.Value = Value("01.44")
    val horses: types.Sector.Value = Value("01.43")
    val poultry: types.Sector.Value = Value("01.47")
    val sheep: types.Sector.Value = Value("01.45")
    val swine: types.Sector.Value = Value("01.46")
    val otherAnimals: types.Sector.Value = Value("01.48")
    val mixedFarming: types.Sector.Value = Value("01.5")
    val mixedFarming4: types.Sector.Value = Value("01.50")
    val supportActivities: types.Sector.Value = Value("01.6")
    val postHarvestActivities: types.Sector.Value = Value("01.63")
    val supportActivitiesAnimal: types.Sector.Value = Value("01.62")
    val supportActivitiesCrop: types.Sector.Value = Value("01.61")
    val huntingTrapping: types.Sector.Value = Value("01.7")
    val huntingTrapping4: types.Sector.Value = Value("01.70")

    val forestry: types.Sector.Value = Value("02")
    val silviculture: types.Sector.Value = Value("02.1")
    val silviculture4: types.Sector.Value = Value("02.10")
    val logging: types.Sector.Value = Value("02.2")
    val logging4: types.Sector.Value = Value("02.20")
    val gatheringOfWildGrowth: types.Sector.Value = Value("02.3")
    val gatheringOfWildGrowth4: types.Sector.Value = Value("02.30")
    val forestrySupportServices: types.Sector.Value = Value("02.4")
    val forestrySupportServices4: types.Sector.Value = Value("02.40")

    val fishingAndAquaculture: types.Sector.Value = Value("03")
    val fishing: types.Sector.Value = Value("03.1")
    val freshwaterFishing: types.Sector.Value = Value("03.12")
    val marineFishing: types.Sector.Value = Value("03.11")
    val aquaculture3: types.Sector.Value = Value("03.2")
    val freshwaterAquaculture: types.Sector.Value = Value("03.22")
    val marineAquaculture: types.Sector.Value = Value("03.21")
    val aquacultureSupportActivities: types.Sector.Value = Value("03.3")
    val aquacultureSupportActivities4: types.Sector.Value = Value("03.30")

    val miningQuarrying: types.Sector.Value = Value("B")
    val coalAndLigniteMining: types.Sector.Value = Value("05")
    val hardcoal: types.Sector.Value = Value("05.1")
    val hardcoalMining: types.Sector.Value = Value("05.10")
    val lignite: types.Sector.Value = Value("05.2")
    val ligniteMining: types.Sector.Value = Value("05.20")
    val petroleumNaturalGasExtraction: types.Sector.Value = Value("06")
    val crudePetroleum: types.Sector.Value = Value("06.1")
    val crudePetroleumExtraction: types.Sector.Value = Value("06.10")
    val naturalGas: types.Sector.Value = Value("06.2")
    val naturalGasExtraction: types.Sector.Value = Value("06.20")
    val metalOresMining: types.Sector.Value = Value("07")
    val ironOre: types.Sector.Value = Value("07.1")
    val ironOresMining: types.Sector.Value = Value("07.10")
    val nonFerrousOres: types.Sector.Value = Value("07.2")
    val uraniumThoriumOres: types.Sector.Value = Value("07.21")
    val otherNonFerrousOres: types.Sector.Value = Value("07.29")
    val otherMiningQuarrying: types.Sector.Value = Value("08")
    val stoneQuarrying: types.Sector.Value = Value("08.1")
    val gravelPitsOperation: types.Sector.Value = Value("08.12")
    val ornamentalQuarrying: types.Sector.Value = Value("08.11")
    val miningAndQuarryingNEC: types.Sector.Value = Value("08.9")
    val peatExtraction: types.Sector.Value = Value("08.92")
    val saltExtraction: types.Sector.Value = Value("08.93")
    val chemicalMineralsMining: types.Sector.Value = Value("08.91")
    val otherNEC: types.Sector.Value = Value("08.99")
    val miningSupportServices: types.Sector.Value = Value("09")
    val miningSupportPetroleumExtraction: types.Sector.Value = Value("09.1")
    val miningSupportPetroleumExtraction4: types.Sector.Value = Value("09.10")
    val otherMiningSupport: types.Sector.Value = Value("09.9")
    val otherMiningSupport4: types.Sector.Value = Value("09.90")

    val manufacturing: types.Sector.Value = Value("C")
    val food: types.Sector.Value = Value("10")
    val meat: types.Sector.Value = Value("10.1")
    val meatProcessing: types.Sector.Value = Value("10.11")
    val poultryProcessing: types.Sector.Value = Value("10.12")
    val meatProductsProduction: types.Sector.Value = Value("10.13")
    val fish: types.Sector.Value = Value("10.2")
    val fishProcessing: types.Sector.Value = Value("10.20")
    val fruitAndVegetables: types.Sector.Value = Value("10.3")
    val fruitAndVegetableJuiceManufacture: types.Sector.Value = Value("10.32")
    val fruitAndVegetableProcessing: types.Sector.Value = Value("10.31")
    val otherFruitAndVegetableProcessing: types.Sector.Value = Value("10.39")
    val oils: types.Sector.Value = Value("10.4")
    val margarine: types.Sector.Value = Value("10.42")
    val otherOils: types.Sector.Value = Value("10.41")
    val dairyProducts: types.Sector.Value = Value("10.5")
    val dairyProducts4: types.Sector.Value = Value("10.51")
    val iceCream: types.Sector.Value = Value("10.52")
    val grainAndStarchProducts: types.Sector.Value = Value("10.6")
    val grainProducts4: types.Sector.Value = Value("10.61")
    val starchProducts: types.Sector.Value = Value("10.62")
    val bakeryProducts: types.Sector.Value = Value("10.7")
    val biscuitsAndPreservedCakes: types.Sector.Value = Value("10.72")
    val breadAndFreshPastry: types.Sector.Value = Value("10.71")
    val farinaceousProducts: types.Sector.Value = Value("10.73")
    val otherFoodProducts: types.Sector.Value = Value("10.8")
    val confectionery: types.Sector.Value = Value("10.82")
    val condiments: types.Sector.Value = Value("10.84")
    val homogenisedFoodPreparations: types.Sector.Value = Value("10.86")
    val preparedMeals: types.Sector.Value = Value("10.85")
    val sugar: types.Sector.Value = Value("10.81")
    val teaAndCoffee: types.Sector.Value = Value("10.83")
    val otherFoodProduct: types.Sector.Value = Value("10.89")
    val preparedAnimalFeeds: types.Sector.Value = Value("10.9")
    val farmAnimalsFood: types.Sector.Value = Value("10.91")
    val petFood: types.Sector.Value = Value("10.92")

    val beverages: types.Sector.Value = Value("11")
    val beverageManufacture: types.Sector.Value = Value("11.0")
    val beer: types.Sector.Value = Value("11.05")
    val ciders: types.Sector.Value = Value("11.03")
    val malt: types.Sector.Value = Value("11.06")
    val softDrinks: types.Sector.Value = Value("11.07")
    val spirits: types.Sector.Value = Value("11.01")
    val wine: types.Sector.Value = Value("11.02")
    val otherFermentedBeverages: types.Sector.Value = Value("11.04")

    val tobaccoProducts: types.Sector.Value = Value("12")
    val tobaccoProductsManufacture3: types.Sector.Value = Value("12.0")
    val tobaccoProductsManufacture4: types.Sector.Value = Value("12.00")

    val textiles: types.Sector.Value = Value("13")
    val textilesPreparation: types.Sector.Value = Value("13.1")
    val textilesPreparation4: types.Sector.Value = Value("13.10")
    val textilesWeaving: types.Sector.Value = Value("13.2")
    val textilesWeaving4: types.Sector.Value = Value("13.20")
    val textilesFinishing: types.Sector.Value = Value("13.3")
    val textilesFinishing4: types.Sector.Value = Value("13.30")
    val textilesManufacture: types.Sector.Value = Value("13.9")
    val carpets: types.Sector.Value = Value("13.93")
    val cordage: types.Sector.Value = Value("13.94")
    val householdTextiles: types.Sector.Value = Value("13.92")
    val knittedFabrics: types.Sector.Value = Value("13.91")
    val nonWoven: types.Sector.Value = Value("13.95")
    val otherTechnicalTextiles: types.Sector.Value = Value("13.96")
    val otherTextile: types.Sector.Value = Value("13.99")

    val clothing: types.Sector.Value = Value("14")
    val knittedCrotchetedClothing: types.Sector.Value = Value("14.1")
    val knittedClothingManufacture: types.Sector.Value = Value("14.10")
    val otherClothing: types.Sector.Value = Value("14.2")
    val leatherAndFurClothing: types.Sector.Value = Value("14.24")
    val outerwear: types.Sector.Value = Value("14.21")
    val underwear: types.Sector.Value = Value("14.22")
    val workwear: types.Sector.Value = Value("14.23")
    val otherClothing4: types.Sector.Value = Value("14.29")

    val leatherProducts: types.Sector.Value = Value("15")
    val leatherManufacture: types.Sector.Value = Value("15.1")
    val luggageManufacture: types.Sector.Value = Value("15.12")
    val leatherTanning: types.Sector.Value = Value("15.11")
    val footwearManufacture: types.Sector.Value = Value("15.2")
    val footwearManufacture4: types.Sector.Value = Value("15.20")

    val woodProducts: types.Sector.Value = Value("16")
    val woodProductsProcessing: types.Sector.Value = Value("16.1")
    val processingAndFinishing: types.Sector.Value = Value("16.12")
    val sawmillingAndPlaning: types.Sector.Value = Value("16.11")
    val woodProductsManufacture: types.Sector.Value = Value("16.2")
    val assembledParquetFloors: types.Sector.Value = Value("16.22")
    val solidFuelsVegetableBiomass: types.Sector.Value = Value("16.26")
    val veneerSheetsPanels: types.Sector.Value = Value("16.21")
    val woodenContainers: types.Sector.Value = Value("16.24")
    val woodenWindowsDoors: types.Sector.Value = Value("16.25")
    val otherBuildersCarpentryJoinery: types.Sector.Value = Value("16.23")
    val otherWoodProducts: types.Sector.Value = Value("16.28")
    val woodenProductsFinishing: types.Sector.Value = Value("16.27")

    val paperRelated: types.Sector.Value = Value("17")
    val pulp: types.Sector.Value = Value("17.1")
    val pulp4: types.Sector.Value = Value("17.11")
    val paper: types.Sector.Value = Value("17.12")
    val articlesPaperBoard: types.Sector.Value = Value("17.2")
    val corrugatedPaperBoardAndContainers: types.Sector.Value = Value("17.21")
    val sanitaryGoods: types.Sector.Value = Value("17.22")
    val paperStationery: types.Sector.Value = Value("17.23")
    val wallpaper: types.Sector.Value = Value("17.24")
    val otherPaper: types.Sector.Value = Value("17.25")

    val printedProducts: types.Sector.Value = Value("18")
    val printingService: types.Sector.Value = Value("18.1")
    val bindingServices: types.Sector.Value = Value("18.14")
    val preMediaServices: types.Sector.Value = Value("18.13")
    val newspapersPrinting: types.Sector.Value = Value("18.11")
    val otherPrinting: types.Sector.Value = Value("18.12")
    val recordedMediaReproduction: types.Sector.Value = Value("18.2")
    val recordedMediaReproduction4: types.Sector.Value = Value("18.20")

    val cokeProducts: types.Sector.Value = Value("19")
    val ovenCokeProducts: types.Sector.Value = Value("19.1")
    val cokeProductsManufacture: types.Sector.Value = Value("19.10")
    val fossilFuelProducts: types.Sector.Value = Value("19.2")
    val fossilFuelProductsManufacture: types.Sector.Value = Value("19.20")

    val chemicalProducts: types.Sector.Value = Value("20")
    val basicChemicalProducts: types.Sector.Value = Value("20.1")
    val dyes: types.Sector.Value = Value("20.12")
    val fertilisers: types.Sector.Value = Value("20.15")
    val industrialGases: types.Sector.Value = Value("20.11")
    val primaryFormsPlastics: types.Sector.Value = Value("20.16")
    val syntheticRubber: types.Sector.Value = Value("20.17")
    val otherInorganicChemicals: types.Sector.Value = Value("20.13")
    val otherOrganicChemicals: types.Sector.Value = Value("20.14")
    val pesticidesDisinfectants: types.Sector.Value = Value("20.2")
    val pesticidesDisinfectantsManufacture: types.Sector.Value = Value("20.20")
    val paintsVarnishesCoatings: types.Sector.Value = Value("20.3")
    val paintsVarnishesCoatingsManufacture: types.Sector.Value = Value("20.30")
    val washingCleaning: types.Sector.Value = Value("20.4")
    val perfumesToiletPreparations: types.Sector.Value = Value("20.42")
    val soap: types.Sector.Value = Value("20.41")
    val otherChemicalProducts: types.Sector.Value = Value("20.5")
    val liquidBiofuels: types.Sector.Value = Value("20.51")
    val otherChemicalProducts4: types.Sector.Value = Value("20.59")
    val manMadeFibre: types.Sector.Value = Value("20.6")
    val manMadeFibreManufacture: types.Sector.Value = Value("20.60")

    val pharmaceuticals: types.Sector.Value = Value("21")
    val basicPharmaceuticals: types.Sector.Value = Value("21.1")
    val pharmaceuticalsManufacture: types.Sector.Value = Value("21.10")
    val pharmaceuticalPreparations: types.Sector.Value = Value("21.2")
    val pharmaceuticalPreparationsManufacture: types.Sector.Value = Value("21.20")

    val rubberPlasticProducts: types.Sector.Value = Value("22")
    val rubberProducts: types.Sector.Value = Value("22.1")
    val rubberTubes: types.Sector.Value = Value("22.11")
    val otherRubberProducts: types.Sector.Value = Value("22.12")
    val plasticProducts: types.Sector.Value = Value("22.2")
    val buildersWare: types.Sector.Value = Value("22.24")
    val doorsAndWindows: types.Sector.Value = Value("22.23")
    val packingGoods: types.Sector.Value = Value("22.22")
    val plasticPlatesSheetsTubes: types.Sector.Value = Value("22.21")
    val otherPlasticProduct: types.Sector.Value = Value("22.26")
    val finishingPlasticProducts: types.Sector.Value = Value("22.25")

    val otherNonMetallicProducts: types.Sector.Value = Value("23")
    val glassProducts: types.Sector.Value = Value("23.1")
    val flatGlass: types.Sector.Value = Value("23.11")
    val glassFibres: types.Sector.Value = Value("23.14")
    val hollowGlass: types.Sector.Value = Value("23.13")
    val otherGlassProducts: types.Sector.Value = Value("23.15")
    val shapingFlatGlass: types.Sector.Value = Value("23.12")
    val refractoryProducts: types.Sector.Value = Value("23.2")
    val refractoryProductsManufacture: types.Sector.Value = Value("23.20")
    val clayBuildingMaterials: types.Sector.Value = Value("23.3")
    val bricks: types.Sector.Value = Value("23.32")
    val ceramicTiles: types.Sector.Value = Value("23.31")
    val otherCeramicProducts: types.Sector.Value = Value("23.4")
    val ceramicHousehold: types.Sector.Value = Value("23.41")
    val ceramicInsulating: types.Sector.Value = Value("23.43")
    val ceramicSanitary: types.Sector.Value = Value("23.42")
    val otherTechnicalCeramicProducts: types.Sector.Value = Value("23.44")
    val otherCeramicProducts4: types.Sector.Value = Value("23.45")
    val cementLimePlaster: types.Sector.Value = Value("23.5")
    val cement: types.Sector.Value = Value("23.51")
    val plasterLime: types.Sector.Value = Value("23.52")
    val cementPlasterArticles: types.Sector.Value = Value("23.6")
    val concreteProducts: types.Sector.Value = Value("23.61")
    val fibreCement: types.Sector.Value = Value("23.65")
    val mortars: types.Sector.Value = Value("23.64")
    val plasterProducts: types.Sector.Value = Value("23.62")
    val readyMixedConcrete: types.Sector.Value = Value("23.63")
    val otherConcreteProducts: types.Sector.Value = Value("23.66")
    val stoneCuttingFinishing: types.Sector.Value = Value("23.7")
    val stoneCuttingFinishing4: types.Sector.Value = Value("23.70")
    val otherAbrasiveProducts: types.Sector.Value = Value("23.9")
    val abrasiveProducts: types.Sector.Value = Value("23.91")
    val otherNonMetallicMineral: types.Sector.Value = Value("23.99")

    val basicMetals: types.Sector.Value = Value("24")
    val basicIronSteel: types.Sector.Value = Value("24.1")
    val basicIronSteelManufacture: types.Sector.Value = Value("24.10")
    val steelTubesFittings: types.Sector.Value = Value("24.2")
    val steelTubesFittingsManufacture: types.Sector.Value = Value("24.20")
    val otherSteelProductsProcessing: types.Sector.Value = Value("24.3")
    val barsColdDrawing: types.Sector.Value = Value("24.31")
    val wireColdDrawing: types.Sector.Value = Value("24.34")
    val foldingColdDrawing: types.Sector.Value = Value("24.33")
    val narrowStripColdDrawing: types.Sector.Value = Value("24.32")
    val basicPreciousAndNonFerrousMetals: types.Sector.Value = Value("24.4")
    val nuclearFuelProcessing: types.Sector.Value = Value("24.46")
    val aluminiumProduction: types.Sector.Value = Value("24.42")
    val copperProduction: types.Sector.Value = Value("24.44")
    val leadZincTinProduction: types.Sector.Value = Value("24.43")
    val preciousMetalsProduction: types.Sector.Value = Value("24.41")
    val nonFerrousMetalsProduction: types.Sector.Value = Value("24.45")
    val metalsCasting: types.Sector.Value = Value("24.5")
    val iron: types.Sector.Value = Value("24.51")
    val lightMetals: types.Sector.Value = Value("24.53")
    val steel: types.Sector.Value = Value("24.52")
    val otherMetals: types.Sector.Value = Value("24.54")

    val fabricatedMetalProducts: types.Sector.Value = Value("25")
    val fabricatedStructuralMetalProducts: types.Sector.Value = Value("25.1")
    val metalDoors: types.Sector.Value = Value("25.12")
    val metalStructures: types.Sector.Value = Value("25.11")
    val metalTanksManufacture: types.Sector.Value = Value("25.2")
    val centralHeating: types.Sector.Value = Value("25.21")
    val otherMetalTanks: types.Sector.Value = Value("25.22")
    val weaponsManufacture: types.Sector.Value = Value("25.3")
    val weaponsManufacture4: types.Sector.Value = Value("25.30")
    val metalForging: types.Sector.Value = Value("25.4")
    val metalForging4: types.Sector.Value = Value("25.40")
    val metalTreatmentCoating: types.Sector.Value = Value("25.5")
    val coating: types.Sector.Value = Value("25.51")
    val heatTreatment: types.Sector.Value = Value("25.52")
    val machining: types.Sector.Value = Value("25.53")
    val cutleryToolsManufacture: types.Sector.Value = Value("25.6")
    val cutlery: types.Sector.Value = Value("25.61")
    val locks: types.Sector.Value = Value("25.62")
    val tools: types.Sector.Value = Value("25.63")
    val otherFabricatedMetalProductsManufacture: types.Sector.Value = Value("25.9")
    val fastenerProducts: types.Sector.Value = Value("25.94")
    val lightMetalPackaging: types.Sector.Value = Value("25.92")
    val steelDrums: types.Sector.Value = Value("25.91")
    val wireProducts: types.Sector.Value = Value("25.93")
    val otherFabricatedMetalProducts: types.Sector.Value = Value("25.99")

    val computersProducts: types.Sector.Value = Value("26")
    val electronicComponents: types.Sector.Value = Value("26.1")
    val electronicComponents4: types.Sector.Value = Value("26.11")
    val loadedElectronicBoards: types.Sector.Value = Value("26.12")
    val computersPeripheralEquipment: types.Sector.Value = Value("26.2")
    val computersPeripheralEquipment4: types.Sector.Value = Value("26.20")
    val communicationEquipment: types.Sector.Value = Value("26.3")
    val communicationEquipment4: types.Sector.Value = Value("26.30")
    val consumerElectronics: types.Sector.Value = Value("26.4")
    val consumerElectronics4: types.Sector.Value = Value("26.40")
    val measuringToolsAndClocks: types.Sector.Value = Value("26.5")
    val measuringInstruments: types.Sector.Value = Value("26.51")
    val watchesAndClocks: types.Sector.Value = Value("26.52")
    val irradiationElectromedicalAndElectrotherapeuticEquipment: types.Sector.Value = Value("26.6")
    val irradiationElectromedicalAndElectrotherapeuticEquipment4: types.Sector.Value = Value("26.60")
    val opticalEquipment: types.Sector.Value = Value("26.7")
    val opticalEquipment4: types.Sector.Value = Value("26.70")

    val electricalEquipment: types.Sector.Value = Value("27")
    val electricMotorsGenerators: types.Sector.Value = Value("27.1")
    val electricMotors: types.Sector.Value = Value("27.11")
    val electricityDistributionAndControl: types.Sector.Value = Value("27.12")
    val batteries: types.Sector.Value = Value("27.2")
    val batteriesManufacture: types.Sector.Value = Value("27.20")
    val wiring: types.Sector.Value = Value("27.3")
    val fibreOpticCables: types.Sector.Value = Value("27.31")
    val otherElectronicWires: types.Sector.Value = Value("27.32")
    val wiringDevices: types.Sector.Value = Value("27.33")
    val lightingEquipment: types.Sector.Value = Value("27.4")
    val lightingEquipmentManufacture: types.Sector.Value = Value("27.40")
    val domesticAppliances: types.Sector.Value = Value("27.5")
    val electricDomesticAppliances: types.Sector.Value = Value("27.51")
    val nonElectricDomesticAppliances: types.Sector.Value = Value("27.52")
    val otherElectricalEquipment: types.Sector.Value = Value("27.9")
    val otherElectricalEquipmentManufacture: types.Sector.Value = Value("27.90")

    val otherMachineryAndEquipment: types.Sector.Value = Value("28")
    val generalPurposeMachinery: types.Sector.Value = Value("28.1")
    val bearings: types.Sector.Value = Value("28.15")
    val engines: types.Sector.Value = Value("28.11")
    val fluidPowerEquipment: types.Sector.Value = Value("28.12")
    val otherPumps: types.Sector.Value = Value("28.13")
    val otherTaps: types.Sector.Value = Value("28.14")
    val otherGeneralPurposeMachinery: types.Sector.Value = Value("28.2")
    val liftingEquipment: types.Sector.Value = Value("28.22")
    val nonDomesticAirConditioning: types.Sector.Value = Value("28.25")
    val officeMachinery: types.Sector.Value = Value("28.23")
    val ovens: types.Sector.Value = Value("28.21")
    val powerDrivenHandTools: types.Sector.Value = Value("28.24")
    val otherGeneralPurposeMachinery4: types.Sector.Value = Value("28.29")
    val agriculturalMachinery: types.Sector.Value = Value("28.3")
    val agriculturalMachineryManufacture: types.Sector.Value = Value("28.30")
    val metalFormingMachinery: types.Sector.Value = Value("28.4")
    val metalFormingMachinery4: types.Sector.Value = Value("28.41")
    val otherMachineTools: types.Sector.Value = Value("28.42")
    val otherSpecialPurposeMachinery: types.Sector.Value = Value("28.9")
    val additiveManufacturingMachinery: types.Sector.Value = Value("28.97")
    val foodMachinery: types.Sector.Value = Value("28.93")
    val metallurgyMachinery: types.Sector.Value = Value("28.91")
    val miningMachinery: types.Sector.Value = Value("28.92")
    val paperMachinery: types.Sector.Value = Value("28.95")
    val textileMachinery: types.Sector.Value = Value("28.94")
    val plasticsMachinery: types.Sector.Value = Value("28.96")
    val otherSpecialPurposeMachinery4: types.Sector.Value = Value("28.99")

    val motorVehicles: types.Sector.Value = Value("29")
    val motorVehicles3: types.Sector.Value = Value("29.1")
    val motorVehiclesManufacture: types.Sector.Value = Value("29.10")
    val motorVehiclesBodies: types.Sector.Value = Value("29.2")
    val motorVehiclesBodies4: types.Sector.Value = Value("29.20")
    val motorVehiclesParts: types.Sector.Value = Value("29.3")
    val motorVehiclesElectricalManufacture: types.Sector.Value = Value("29.31")
    val motorVehiclesOtherManufacture: types.Sector.Value = Value("29.32")

    val otherTransportEquipment: types.Sector.Value = Value("30")
    val ships: types.Sector.Value = Value("30.1")
    val civilianShips: types.Sector.Value = Value("30.11")
    val militaryShips: types.Sector.Value = Value("30.13")
    val pleasureShips: types.Sector.Value = Value("30.12")
    val railway: types.Sector.Value = Value("30.2")
    val railwayManufacture: types.Sector.Value = Value("30.20")
    val aircraft: types.Sector.Value = Value("30.3")
    val civilianAircraftMachinery: types.Sector.Value = Value("30.31")
    val militaryAircraftMachinery: types.Sector.Value = Value("30.32")
    val militaryFightingVehicles: types.Sector.Value = Value("30.4")
    val militaryFightingVehiclesManufacture: types.Sector.Value = Value("30.40")
    val otherTransportEquipment3: types.Sector.Value = Value("30.9")
    val bicycles: types.Sector.Value = Value("30.92")
    val motorcyclesEquipment: types.Sector.Value = Value("30.91")
    val otherTransportEquipment4: types.Sector.Value = Value("30.99")

    val furnitureManufacture: types.Sector.Value = Value("31")
    val furnitureManufacture3: types.Sector.Value = Value("31.0")
    val furnitureManufacture4: types.Sector.Value = Value("31.00")

    val otherManufacturing: types.Sector.Value = Value("32")
    val jewelleryAndCoins: types.Sector.Value = Value("32.1")
    val jewelleryManufacture: types.Sector.Value = Value("32.12")
    val imitationJewelleryManufacture: types.Sector.Value = Value("32.13")
    val coinStriking: types.Sector.Value = Value("32.11")
    val musicalInstruments: types.Sector.Value = Value("32.2")
    val musicalInstrumentsManufacture: types.Sector.Value = Value("32.20")
    val sportsGoods: types.Sector.Value = Value("32.3")
    val sportsGoodsManufacture: types.Sector.Value = Value("32.30")
    val gamesAndToys: types.Sector.Value = Value("32.4")
    val gamesAndToysManufacture: types.Sector.Value = Value("32.40")
    val medicalInstruments: types.Sector.Value = Value("32.5")
    val medicalInstrumentsManufacture: types.Sector.Value = Value("32.50")
    val otherProducts: types.Sector.Value = Value("32.9")
    val broomsAndBrushes: types.Sector.Value = Value("32.91")
    val otherProductManufacture: types.Sector.Value = Value("32.99")

    val metalProductsRepairMaintenance: types.Sector.Value = Value("33")
    val fabricatedMetalProductsRepair: types.Sector.Value = Value("33.1")
    val civilianAirRepair: types.Sector.Value = Value("33.16")
    val civilianShipsRepair: types.Sector.Value = Value("33.15")
    val otherCivilianTransportEquipmentRepair: types.Sector.Value = Value("33.17")
    val electricalEquipmentRepair: types.Sector.Value = Value("33.14")
    val electronicEquipmentRepair: types.Sector.Value = Value("33.13")
    val fabricatedMetalProducts4: types.Sector.Value = Value("33.11")
    val machineryRepair: types.Sector.Value = Value("33.12")
    val militaryVehiclesRepair: types.Sector.Value = Value("33.18")
    val otherEquipmentRepair: types.Sector.Value = Value("33.19")
    val industrialMachineryInstallation: types.Sector.Value = Value("33.2")
    val industrialMachineryInstallation4: types.Sector.Value = Value("33.20")

    val electricityGas: types.Sector.Value = Value("D")
    val electricityGasAirConditioningSupply: types.Sector.Value = Value("35")
    val electricPowerGenerationAndDistribution: types.Sector.Value = Value("35.1")
    val electricityDistribution: types.Sector.Value = Value("35.14")
    val nonRenewableElectricityProduction: types.Sector.Value = Value("35.11")
    val renewableElectricityProduction: types.Sector.Value = Value("35.12")
    val electricityStorage: types.Sector.Value = Value("35.16")
    val electricityTrade: types.Sector.Value = Value("35.15")
    val electricityTransmission: types.Sector.Value = Value("35.13")
    val gaseousFuelsManufacture: types.Sector.Value = Value("35.2")
    val gaseousFuelDistribution: types.Sector.Value = Value("35.22")
    val gaseousFuelManufacture: types.Sector.Value = Value("35.21")
    val gaseousFuelStorage: types.Sector.Value = Value("35.24")
    val gaseousFuelTrade: types.Sector.Value = Value("35.23")
    val steamAndAirConditioningSupply: types.Sector.Value = Value("35.3")
    val steamAndAirConditioningSupply4: types.Sector.Value = Value("35.30")
    val electricPowerAndGasBrokers: types.Sector.Value = Value("35.4")
    val electricPowerAndGasBrokers4: types.Sector.Value = Value("35.40")

    val waterSupply: types.Sector.Value = Value("E")
    val waterTreatment: types.Sector.Value = Value("36")
    val waterTreatment3: types.Sector.Value = Value("36.0")
    val waterTreatment4: types.Sector.Value = Value("36.00")
    val sewerage: types.Sector.Value = Value("37")
    val sewerage3: types.Sector.Value = Value("37.0")
    val sewerage4: types.Sector.Value = Value("37.00")
    val wasteManagement: types.Sector.Value = Value("38")
    val wasteCollection: types.Sector.Value = Value("38.1")
    val hazardousWaste: types.Sector.Value = Value("38.12")
    val nonHazardousWaste: types.Sector.Value = Value("38.11")
    val wasteRecovery: types.Sector.Value = Value("38.2")
    val energyRecovery: types.Sector.Value = Value("38.22")
    val materialsRecovery: types.Sector.Value = Value("38.21")
    val otherWasteRecovery: types.Sector.Value = Value("38.23")
    val wasteDisposal: types.Sector.Value = Value("38.3")
    val incineration: types.Sector.Value = Value("38.31")
    val landFilling: types.Sector.Value = Value("38.32")
    val otherWasteDisposal: types.Sector.Value = Value("38.33")
    val wasteManagementRemediation: types.Sector.Value = Value("39")
    val wasteManagementRemediation3: types.Sector.Value = Value("39.0")
    val wasteManagementRemediation4: types.Sector.Value = Value("39.00")

    val construction: types.Sector.Value = Value("F")
    val residentialNonResidentialConstruction: types.Sector.Value = Value("41")
    val residentialNonResidentialConstruction3: types.Sector.Value = Value("41.0")
    val residentialNonResidentialConstruction4: types.Sector.Value = Value("41.00")

    val civilEngineering: types.Sector.Value = Value("42")
    val roadAndRailConstruction: types.Sector.Value = Value("42.1")
    val bridgesTunnels: types.Sector.Value = Value("42.13")
    val railwaysUnderground: types.Sector.Value = Value("42.12")
    val roadsMotorways: types.Sector.Value = Value("42.11")
    val utilityConstruction: types.Sector.Value = Value("42.2")
    val electricityUtilityConstruction: types.Sector.Value = Value("42.22")
    val fluidsUtilityConstruction: types.Sector.Value = Value("42.21")
    val otherUtilityConstructionProjects: types.Sector.Value = Value("42.9")
    val waterProjects: types.Sector.Value = Value("42.91")
    val otherCivilEngineering: types.Sector.Value = Value("42.99")

    val specialisedConstructionActivities: types.Sector.Value = Value("43")
    val demolitionAndPreparation: types.Sector.Value = Value("43.1")
    val demolition: types.Sector.Value = Value("43.11")
    val sitePreparation: types.Sector.Value = Value("43.12")
    val testDrillingBoring: types.Sector.Value = Value("43.13")
    val electricalAndPlumbingInstallation: types.Sector.Value = Value("43.2")
    val electricalInstallation: types.Sector.Value = Value("43.21")
    val insulationInstallation: types.Sector.Value = Value("43.23")
    val plumbingHeatingAC: types.Sector.Value = Value("43.22")
    val otherConstructionInstallation: types.Sector.Value = Value("43.24")
    val buildingFinishing: types.Sector.Value = Value("43.3")
    val floorAndWallCovering: types.Sector.Value = Value("43.33")
    val joineryInstallation: types.Sector.Value = Value("43.32")
    val paintingAndGlazing: types.Sector.Value = Value("43.34")
    val plastering: types.Sector.Value = Value("43.31")
    val otherBuildingFinishing: types.Sector.Value = Value("43.35")
    val specialisedBuildingActivities: types.Sector.Value = Value("43.4")
    val roofingActivities: types.Sector.Value = Value("43.41")
    val otherSpecialisedBuildingActivities: types.Sector.Value = Value("43.42")
    val specialisedCivilEngineering: types.Sector.Value = Value("43.5")
    val specialisedCivilEngineering4: types.Sector.Value = Value("43.50")
    val specialisedConstructionIntermediationServices: types.Sector.Value = Value("43.6")
    val specialisedConstructionIntermediationServices4: types.Sector.Value = Value("43.60")
    val otherSpecialisedConstruction: types.Sector.Value = Value("43.9")
    val masonryAndBricklaying: types.Sector.Value = Value("43.91")
    val otherSpecialisedConstructionActivities: types.Sector.Value = Value("43.99")

    val wholesaleAndRetailTrade: types.Sector.Value = Value("G")
    val Wholesale: types.Sector.Value = Value("46")
    val WholesaleContractBasis: types.Sector.Value = Value("46.1")
    val AgriculturalWholesaleContractBasis: types.Sector.Value = Value("46.11")
    val FoodWholesaleContractBasis: types.Sector.Value = Value("46.17")
    val FuelsWholesaleContractBasis: types.Sector.Value = Value("46.12")
    val FurnitureWholesaleContractBasis: types.Sector.Value = Value("46.15")
    val MachineryWholesaleContractBasis: types.Sector.Value = Value("46.14")
    val TextilesWholesaleContractBasis: types.Sector.Value = Value("46.16")
    val TimberWholesaleContractBasis: types.Sector.Value = Value("46.13")
    val OtherWholesaleContractBasis: types.Sector.Value = Value("46.18")
    val NonSpecialisedWholesaleContractBasis: types.Sector.Value = Value("46.19")
    val AgriculturalWholesale: types.Sector.Value = Value("46.2")
    val FlowersAndPlants: types.Sector.Value = Value("46.22")
    val Grain: types.Sector.Value = Value("46.21")
    val LeatherWholesale: types.Sector.Value = Value("46.24")
    val LiveAnimals: types.Sector.Value = Value("46.23")
    val FoodWholesale: types.Sector.Value = Value("46.3")
    val BeveragesWholesale: types.Sector.Value = Value("46.34")
    val CoffeeAndSpicesWholesale: types.Sector.Value = Value("46.37")
    val DairyProductsWholesale: types.Sector.Value = Value("46.33")
    val FruitWholesale: types.Sector.Value = Value("46.31")
    val MeatWholesale: types.Sector.Value = Value("46.32")
    val SugarWholesale: types.Sector.Value = Value("46.36")
    val TobaccoProductsWholesale: types.Sector.Value = Value("46.35")
    val OtherFoodWholesale: types.Sector.Value = Value("46.38")
    val NonSpecialisedFoodWholesale: types.Sector.Value = Value("46.39")
    val WholesaleHouseholdGoods: types.Sector.Value = Value("46.4")
    val ChinaWholesale: types.Sector.Value = Value("46.44")
    val ClothingWholesale: types.Sector.Value = Value("46.42")
    val ElectricalHouseholdWholesale: types.Sector.Value = Value("46.43")
    val HouseholdWholesale: types.Sector.Value = Value("46.47")
    val PerfumeWholesale: types.Sector.Value = Value("46.45")
    val PharmaceuticalWholesale: types.Sector.Value = Value("46.46")
    val TextilesWholesale: types.Sector.Value = Value("46.41")
    val WatchesWholesale: types.Sector.Value = Value("46.48")
    val OtherHouseholdGoodsWholesale: types.Sector.Value = Value("46.49")
    val InformationEquipmentWholesale: types.Sector.Value = Value("46.5")
    val InformationEquipmentWholesale4: types.Sector.Value = Value("46.50")
    val MachineryWholesale: types.Sector.Value = Value("46.6")
    val AgriculturalMachineryWholesale: types.Sector.Value = Value("46.61")
    val MachineToolsWholesale: types.Sector.Value = Value("46.62")
    val MiningMachineryWholesale: types.Sector.Value = Value("46.63")
    val OtherMachineryWholesale: types.Sector.Value = Value("46.64")
    val MotorVehiclesWholesale: types.Sector.Value = Value("46.7")
    val MotorVehicleWholesale: types.Sector.Value = Value("46.71")
    val MotorVehiclePartsWholesale: types.Sector.Value = Value("46.72")
    val MotorcyclePartsWholesale: types.Sector.Value = Value("46.73")
    val OtherSpecialisedWholesale: types.Sector.Value = Value("46.8")
    val ChemicalProductsWholesale: types.Sector.Value = Value("46.85")
    val HardwareEquipment: types.Sector.Value = Value("46.84")
    val metals: types.Sector.Value = Value("46.82")
    val Fuels: types.Sector.Value = Value("46.81")
    val Waste: types.Sector.Value = Value("46.87")
    val Wood: types.Sector.Value = Value("46.83")
    val OtherIntermediateProducts: types.Sector.Value = Value("46.86")
    val OtherSpecialisedWholesale4: types.Sector.Value = Value("46.89")
    val NonSpecialisedWholesale: types.Sector.Value = Value("46.9")
    val NonSpecialisedWholesaleTrade: types.Sector.Value = Value("46.90")

    val Retail: types.Sector.Value = Value("47")
    val NonSpecialisedRetail: types.Sector.Value = Value("47.1")
    val NonSpecialisedFoodRetail: types.Sector.Value = Value("47.11")
    val OtherNonSpecialisedRetail: types.Sector.Value = Value("47.12")
    val FoodRetail: types.Sector.Value = Value("47.2")
    val BeveragesRetail: types.Sector.Value = Value("47.25")
    val BreadRetail: types.Sector.Value = Value("47.24")
    val FishRetail: types.Sector.Value = Value("47.23")
    val FruitRetail: types.Sector.Value = Value("47.21")
    val MeatRetail: types.Sector.Value = Value("47.22")
    val TobaccoRetail: types.Sector.Value = Value("47.26")
    val OtherFoodRetail: types.Sector.Value = Value("47.27")
    val AutomotiveFuelRetail: types.Sector.Value = Value("47.3")
    val AutomotiveFuelRetail4: types.Sector.Value = Value("47.30")
    val communicationEquipmentRetail: types.Sector.Value = Value("47.4")
    val CommunicationEquipmentRetail4: types.Sector.Value = Value("47.40")
    val OtherHouseholdEquipmentRetail: types.Sector.Value = Value("47.5")
    val CarpetsRetail: types.Sector.Value = Value("47.53")
    val ElectricalRetail: types.Sector.Value = Value("47.54")
    val HardwareRetail: types.Sector.Value = Value("47.52")
    val TextilesRetail: types.Sector.Value = Value("47.51")
    val FurnitureRetail: types.Sector.Value = Value("47.55")
    val CulturalRetail: types.Sector.Value = Value("47.6")
    val BooksRetail: types.Sector.Value = Value("47.61")
    val GamesRetail: types.Sector.Value = Value("47.64")
    val NewspapersRetail: types.Sector.Value = Value("47.62")
    val SportingEquipmentRetail: types.Sector.Value = Value("47.63")
    val OtherCulturalAndRecreationalGoods: types.Sector.Value = Value("47.69")
    val OtherGoodsRetail: types.Sector.Value = Value("47.7")
    val ClothingRetail: types.Sector.Value = Value("47.71")
    val CosmeticRetail: types.Sector.Value = Value("47.75")
    val FlowersRetail: types.Sector.Value = Value("47.76")
    val FootwearRetail: types.Sector.Value = Value("47.72")
    val MedicalRetail: types.Sector.Value = Value("47.74")
    val PharmaceuticalRetail: types.Sector.Value = Value("47.73")
    val WatchesRetail: types.Sector.Value = Value("47.77")
    val OtherNewGoodsRetail: types.Sector.Value = Value("47.78")
    val SecondHandGoods: types.Sector.Value = Value("47.79")
    val MotorVehiclesAndMotorcyclesRetail: types.Sector.Value = Value("47.8")
    val MotorVehiclesRetail: types.Sector.Value = Value("47.81")
    val MotorVehiclesPartsRetail: types.Sector.Value = Value("47.82")
    val MotorcyclesRetail: types.Sector.Value = Value("47.83")
    val RetailIntermediationServices: types.Sector.Value = Value("47.9")
    val NonSpecialisedRetailIntermediation: types.Sector.Value = Value("47.91")
    val SpecialisedRetailIntermediation: types.Sector.Value = Value("47.92")

    val transportStorage: types.Sector.Value = Value("H")
    val landTransport: types.Sector.Value = Value("49")
    val passengerRailTransport: types.Sector.Value = Value("49.1")
    val passengerHeavyRailTransport: types.Sector.Value = Value("49.11")
    val otherPassengerRailTransport: types.Sector.Value = Value("49.12")
    val freightRailTransport: types.Sector.Value = Value("49.2")
    val freightRailTransport4: types.Sector.Value = Value("49.20")
    val otherPassengerLandTransport: types.Sector.Value = Value("49.3")
    val nonScheduledPassengerRoadTransport: types.Sector.Value = Value("49.32")
    val onDemandPassengerRoadTransport: types.Sector.Value = Value("49.33")
    val cablewaysPassengerTransport: types.Sector.Value = Value("49.34")
    val scheduledPassengerRoadTransport: types.Sector.Value = Value("49.31")
    val otherLandTransport: types.Sector.Value = Value("49.39")
    val freightRoadTransport: types.Sector.Value = Value("49.4")
    val freightRoadTransport4: types.Sector.Value = Value("49.41")
    val removalServices: types.Sector.Value = Value("49.42")
    val pipelineTransport: types.Sector.Value = Value("49.5")
    val pipelineTransport4: types.Sector.Value = Value("49.50")

    val waterTransport: types.Sector.Value = Value("50")
    val coastalPassengerWaterTransport: types.Sector.Value = Value("50.1")
    val coastalPassengerWaterTransport4: types.Sector.Value = Value("50.10")
    val coastalFreightWaterTransport: types.Sector.Value = Value("50.2")
    val coastalFreightWaterTransport4: types.Sector.Value = Value("50.20")
    val inlandPassengerWaterTransport: types.Sector.Value = Value("50.3")
    val inlandPassengerWaterTransport4: types.Sector.Value = Value("50.30")
    val inlandFreightWaterTransport: types.Sector.Value = Value("50.4")
    val inlandFreightWaterTransport4: types.Sector.Value = Value("50.40")

    val airTransport: types.Sector.Value = Value("51")
    val passengerAirTransport: types.Sector.Value = Value("51.1")
    val passengerAirTransport4: types.Sector.Value = Value("51.10")
    val freightAndSpaceAirTransport: types.Sector.Value = Value("51.2")
    val freightAirTransport: types.Sector.Value = Value("51.21")
    val spaceTransport: types.Sector.Value = Value("51.22")

    val warehousingStorageTransportSupportActivities: types.Sector.Value = Value("52")
    val warehousingStorage: types.Sector.Value = Value("52.1")
    val warehousingStorage4: types.Sector.Value = Value("52.10")
    val transportSupportActivities: types.Sector.Value = Value("52.2")
    val cargoHandling: types.Sector.Value = Value("52.24")
    val logisticsServiceActivities: types.Sector.Value = Value("52.25")
    val airTransportServiceActivities: types.Sector.Value = Value("52.23")
    val landTransportServiceActivities: types.Sector.Value = Value("52.21")
    val waterTransportServiceActivities: types.Sector.Value = Value("52.22")
    val otherTransportSupportActivities: types.Sector.Value = Value("52.26")
    val transportIntermediationServiceActivities: types.Sector.Value = Value("52.3")
    val freightTransportIntermediationServiceActivities: types.Sector.Value = Value("52.31")
    val passengerTransportIntermediationServiceActivities: types.Sector.Value = Value("52.32")
    val postalAndCourierActivities: types.Sector.Value = Value("53")
    val postalActivities: types.Sector.Value = Value("53.1")
    val postalActivities4: types.Sector.Value = Value("53.10")
    val otherPostalActivities: types.Sector.Value = Value("53.2")
    val otherPostalActivities4: types.Sector.Value = Value("53.20")
    val postalIntermediationActivities: types.Sector.Value = Value("53.3")
    val postalIntermediationActivities4: types.Sector.Value = Value("53.30")

    val accommodationAndFoodService: types.Sector.Value = Value("I")
    val accommodation: types.Sector.Value = Value("55")
    val hotelsAccommodation: types.Sector.Value = Value("55.1")
    val hotelsAccommodation4: types.Sector.Value = Value("55.10")
    val holidayShortStay: types.Sector.Value = Value("55.2")
    val holidayShortStay4: types.Sector.Value = Value("55.20")
    val campingGrounds: types.Sector.Value = Value("55.3")
    val campingGrounds4: types.Sector.Value = Value("55.30")
    val intermediationAccommodation: types.Sector.Value = Value("55.4")
    val intermediationAccommodation4: types.Sector.Value = Value("55.40")
    val otherAccommodation: types.Sector.Value = Value("55.9")
    val otherAccommodation4: types.Sector.Value = Value("55.90")

    val foodBeverageServiceActivities: types.Sector.Value = Value("56")
    val restaurantsMobile: types.Sector.Value = Value("56.1")
    val restaurantsMobile4: types.Sector.Value = Value("56.11")
    val mobileFoodServices: types.Sector.Value = Value("56.12")
    val eventAndContractCatering: types.Sector.Value = Value("56.2")
    val eventCatering: types.Sector.Value = Value("56.21")
    val contractCatering: types.Sector.Value = Value("56.22")
    val beverageServing: types.Sector.Value = Value("56.3")
    val beverageServing4: types.Sector.Value = Value("56.30")
    val foodBeverageServiceIntermediationActivities: types.Sector.Value = Value("56.4")
    val foodBeverageServiceIntermediationActivities4: types.Sector.Value = Value("56.40")

    val publishingBroadcasting: types.Sector.Value = Value("J")
    val publishing: types.Sector.Value = Value("58")
    val publishingBooksNewspapers: types.Sector.Value = Value("58.1")
    val books: types.Sector.Value = Value("58.11")
    val journalsPeriodicals: types.Sector.Value = Value("58.13")
    val newspapers: types.Sector.Value = Value("58.12")
    val otherPublishing: types.Sector.Value = Value("58.19")
    val softwarePublishing: types.Sector.Value = Value("58.2")
    val videoGames: types.Sector.Value = Value("58.21")
    val otherSoftware: types.Sector.Value = Value("58.29")

    val filmVideoSoundPublishing: types.Sector.Value = Value("59")
    val filmVideoActivities: types.Sector.Value = Value("59.1")
    val videoProductionDistribution: types.Sector.Value = Value("59.13")
    val videoPostProduction: types.Sector.Value = Value("59.12")
    val videoProduction: types.Sector.Value = Value("59.11")
    val projection: types.Sector.Value = Value("59.14")
    val soundRecordingAndMusicPublishing: types.Sector.Value = Value("59.2")
    val soundRecordingAndMusicPublishingActivities: types.Sector.Value = Value("59.20")

    val programmingBroadcastingNewsActivities: types.Sector.Value = Value("60")
    val radioBroadcasting: types.Sector.Value = Value("60.1")
    val radioBroadcasting4: types.Sector.Value = Value("60.10")
    val programmingBroadcastingVideoDistribution: types.Sector.Value = Value("60.2")
    val programmingBroadcastingVideoDistribution4: types.Sector.Value = Value("60.20")
    val newsAgency: types.Sector.Value = Value("60.3")
    val newsAgencyActivities: types.Sector.Value = Value("60.31")
    val otherContentDistributionActivities: types.Sector.Value = Value("60.39")

    val telecommunications: types.Sector.Value = Value("K")
    val telecommunication: types.Sector.Value = Value("61")
    val wiredTelecommunication: types.Sector.Value = Value("61.1")
    val wiredTelecommunication4: types.Sector.Value = Value("61.10")
    val resellingTelecommunication: types.Sector.Value = Value("61.2")
    val resellingTelecommunication4: types.Sector.Value = Value("61.20")
    val otherTelecommunications: types.Sector.Value = Value("61.9")
    val otherTelecommunications4: types.Sector.Value = Value("61.90")

    val computerProgrammingConsultancy: types.Sector.Value = Value("62")
    val computerProgrammingActivities: types.Sector.Value = Value("62.1")
    val computerProgrammingActivities4: types.Sector.Value = Value("62.10")
    val computerFacilitiesConsultancy: types.Sector.Value = Value("62.2")
    val computerFacilitiesConsultancy4: types.Sector.Value = Value("62.20")
    val otherComputerServiceActivities: types.Sector.Value = Value("62.9")
    val otherComputerServiceActivities4: types.Sector.Value = Value("62.90")

    val computingInfrastructureActivities: types.Sector.Value = Value("63")
    val computingInfrastructureActivities3: types.Sector.Value = Value("63.1")
    val computingInfrastructureActivities4: types.Sector.Value = Value("63.10")
    val webSearchPortal: types.Sector.Value = Value("63.9")
    val webSearchPortalActivities: types.Sector.Value = Value("63.91")
    val otherInformationServices: types.Sector.Value = Value("63.92")

    val financialInsuranceActivities: types.Sector.Value = Value("L")
    val FinancialServices: types.Sector.Value = Value("64")
    val MonetaryIntermediation: types.Sector.Value = Value("64.1")
    val CentralBanking: types.Sector.Value = Value("64.11")
    val OtherMonetary: types.Sector.Value = Value("64.19")
    val HoldingCompaniesFinal: types.Sector.Value = Value("64.21")
    val FinancingConduits: types.Sector.Value = Value("64.22")
    val HoldingCompanies: types.Sector.Value = Value("64.2")
    val TrustsFunds: types.Sector.Value = Value("64.3")
    val InvestmentFunds: types.Sector.Value = Value("64.31")
    val TrustEstate: types.Sector.Value = Value("64.32")
    val OtherFinancial: types.Sector.Value = Value("64.9")
    val FinancialLeasing: types.Sector.Value = Value("64.91")
    val OtherCredit: types.Sector.Value = Value("64.92")
    val OtherFinancialServices: types.Sector.Value = Value("64.99")

    val InsuranceReinsurancePensionFunding: types.Sector.Value = Value("65")
    val InsuranceServices: types.Sector.Value = Value("65.1")
    val LifeInsurance: types.Sector.Value = Value("65.11")
    val NonLifeInsurance: types.Sector.Value = Value("65.12")
    val ReinsuranceServices: types.Sector.Value = Value("65.2")
    val Reinsurance4: types.Sector.Value = Value("65.20")
    val PensionFundingServices: types.Sector.Value = Value("65.3")
    val PensionFunding4: types.Sector.Value = Value("65.30")

    val auxiliaryActivities: types.Sector.Value = Value("66")
    val AuxiliaryFinancialServices: types.Sector.Value = Value("66.1")
    val FinancialMarkets: types.Sector.Value = Value("66.11")
    val SecurityBrokerage: types.Sector.Value = Value("66.12")
    val OtherAuxiliaryFinancial: types.Sector.Value = Value("66.19")
    val AuxiliaryInsurance: types.Sector.Value = Value("66.2")
    val InsuranceAgents: types.Sector.Value = Value("66.22")
    val RiskEvaluation: types.Sector.Value = Value("66.21")
    val OtherAuxiliaryInsurance: types.Sector.Value = Value("66.29")
    val FundManagementServices: types.Sector.Value = Value("66.3")
    val fundManagementActivities: types.Sector.Value = Value("66.30")

    val realEstate: types.Sector.Value = Value("M")
    val realEstateActivities: types.Sector.Value = Value("68")
    val PropertyDevelopment: types.Sector.Value = Value("68.1")
    val BuyingSelling: types.Sector.Value = Value("68.11")
    val DevelopmentProjects: types.Sector.Value = Value("68.12")
    val RentalOperating: types.Sector.Value = Value("68.2")
    val realEstateRental4: types.Sector.Value = Value("68.20")
    val FeeContract: types.Sector.Value = Value("68.3")
    val Intermediation: types.Sector.Value = Value("68.31")
    val OtherFeeContract: types.Sector.Value = Value("68.32")

    val professionalScientificAndTechnicalActivities: types.Sector.Value = Value("N")
    val legalAndAccounting: types.Sector.Value = Value("69")
    val legal: types.Sector.Value = Value("69.1")
    val legalActivities4: types.Sector.Value = Value("69.10")
    val accounting: types.Sector.Value = Value("69.2")
    val accountingTaxConsultancy: types.Sector.Value = Value("69.20")

    val headOfficesAndManagementConsultancy: types.Sector.Value = Value("70")
    val headOffice: types.Sector.Value = Value("70.1")
    val headOfficesActivities4: types.Sector.Value = Value("70.10")
    val managementConsultancy: types.Sector.Value = Value("70.2")
    val managementConsultancyActivities4: types.Sector.Value = Value("70.20")

    val architecturalAndTechnical: types.Sector.Value = Value("71")
    val architecturalAndTechnicalActivities: types.Sector.Value = Value("71.1")
    val architecturalEngineering: types.Sector.Value = Value("71.11")
    val engineeringConsultancy: types.Sector.Value = Value("71.12")
    val technicalTesting: types.Sector.Value = Value("71.2")
    val technicalTesting4: types.Sector.Value = Value("71.20")

    val scientificResearchAndDevelopment: types.Sector.Value = Value("72")
    val naturalScientificResearchAndDevelopment: types.Sector.Value = Value("72.1")
    val naturalScientificResearchAndDevelopment4: types.Sector.Value = Value("72.10")
    val socialScientificResearchAndDevelopment: types.Sector.Value = Value("72.2")
    val socialScientificResearchAndDevelopment4: types.Sector.Value = Value("72.20")

    val advertisingMarketResearch: types.Sector.Value = Value("73")
    val advertising: types.Sector.Value = Value("73.1")
    val advertisingActivities: types.Sector.Value = Value("73.11")
    val mediaRepresentation: types.Sector.Value = Value("73.12")
    val marketResearch: types.Sector.Value = Value("73.2")
    val marketResearch4: types.Sector.Value = Value("73.20")
    val publicRelations: types.Sector.Value = Value("73.3")
    val publicRelations4: types.Sector.Value = Value("73.30")

    val otherProfessionalScientific: types.Sector.Value = Value("74")
    val specialisedDesign: types.Sector.Value = Value("74.1")
    val graphicDesign: types.Sector.Value = Value("74.12")
    val industrialFashionDesign: types.Sector.Value = Value("74.11")
    val interiorDesign: types.Sector.Value = Value("74.13")
    val otherDesign: types.Sector.Value = Value("74.14")
    val photography: types.Sector.Value = Value("74.2")
    val photographicActivities: types.Sector.Value = Value("74.20")
    val translationInterpretation: types.Sector.Value = Value("74.3")
    val translationActivities4: types.Sector.Value = Value("74.30")
    val otherProfessionalScientificActivities: types.Sector.Value = Value("74.9")
    val patentBrokering: types.Sector.Value = Value("74.91")
    val otherProfessionalScientificActivities4: types.Sector.Value = Value("74.99")

    val veterinary: types.Sector.Value = Value("75")
    val veterinaryActivities3: types.Sector.Value = Value("75.0")
    val veterinaryActivities4: types.Sector.Value = Value("75.00")

    val administration: types.Sector.Value = Value("O")
    val RentalAndLeasing: types.Sector.Value = Value("77")
    val MotorVehiclesRental: types.Sector.Value = Value("77.1")
    val CarsLightVehicles: types.Sector.Value = Value("77.11")
    val Trucks: types.Sector.Value = Value("77.12")
    val PersonalRental: types.Sector.Value = Value("77.2")
    val RecreationalSportsGoods: types.Sector.Value = Value("77.21")
    val OtherPersonalHouseholdGoods: types.Sector.Value = Value("77.22")
    val OtherMachineryRental: types.Sector.Value = Value("77.3")
    val AgriculturalMachineryRental: types.Sector.Value = Value("77.31")
    val AirTransportRental: types.Sector.Value = Value("77.35")
    val ConstructionMachineryRental: types.Sector.Value = Value("77.32")
    val OfficeMachineryRental: types.Sector.Value = Value("77.33")
    val WaterTransportRental: types.Sector.Value = Value("77.34")
    val OtherMachineryRental4: types.Sector.Value = Value("77.39")
    val IntellectualProperty: types.Sector.Value = Value("77.4")
    val LeasingIntellectualProperty: types.Sector.Value = Value("77.40")
    val TangibleGoodsRentalIntermediation: types.Sector.Value = Value("77.5")
    val CarsMotorhomesTrailers: types.Sector.Value = Value("77.51")
    val otherTangibleGoodsRental: types.Sector.Value = Value("77.52")

    val Employment: types.Sector.Value = Value("78")
    val employmentPlacementActivities: types.Sector.Value = Value("78.1")
    val employmentPlacementActivities4: types.Sector.Value = Value("78.10")
    val tempEmploymentPlacementActivities: types.Sector.Value = Value("78.2")
    val tempEmploymentPlacementActivities4: types.Sector.Value = Value("78.20")

    val TravelAgencyAndReservation: types.Sector.Value = Value("79")
    val TravelAgency: types.Sector.Value = Value("79.1")
    val TourOperator: types.Sector.Value = Value("79.12")
    val TravelAgencyActivities: types.Sector.Value = Value("79.11")
    val OtherReservationServices: types.Sector.Value = Value("79.9")
    val OtherReservationServices4: types.Sector.Value = Value("79.90")

    val InvestigationAndSecurity: types.Sector.Value = Value("80")
    val InvestigationAndSecurityActivities: types.Sector.Value = Value("80.0")
    val PrivateInvestigationAndSecurityActivities: types.Sector.Value = Value("80.01")
    val OtherInvestigationAndSecurityActivities: types.Sector.Value = Value("80.09")

    val BuildingsAndLandscapingServices: types.Sector.Value = Value("81")
    val CombinedFacilitiesSupport: types.Sector.Value = Value("81.1")
    val combinedFacilitiesSupport4: types.Sector.Value = Value("81.10")
    val Cleaning: types.Sector.Value = Value("81.2")
    val GeneralCleaning: types.Sector.Value = Value("81.21")
    val IndustrialCleaning: types.Sector.Value = Value("81.22")
    val OtherCleaning: types.Sector.Value = Value("81.23")
    val Landscaping: types.Sector.Value = Value("81.3")
    val landscapeServiceActivities: types.Sector.Value = Value("81.30")

    val OfficeAdministrativeSupport: types.Sector.Value = Value("82")
    val OfficeAdministrative: types.Sector.Value = Value("82.1")
    val officeAdministrativeActivities4: types.Sector.Value = Value("82.10")
    val CallCentres: types.Sector.Value = Value("82.2")
    val callCentresActivities: types.Sector.Value = Value("82.20")
    val conventionsOrganisation: types.Sector.Value = Value("82.3")
    val conventionsOrganisation4: types.Sector.Value = Value("82.30")
    val businessSupportIntermediation: types.Sector.Value = Value("82.4")
    val businessSupportIntermediation4: types.Sector.Value = Value("82.40")
    val otherBusinessSupportIntermediationService: types.Sector.Value = Value("82.9")
    val CollectionAgencies: types.Sector.Value = Value("82.91")
    val PackagingActivities: types.Sector.Value = Value("82.92")
    val OtherBusinessSupport: types.Sector.Value = Value("82.99")

    val publicAdministration: types.Sector.Value = Value("P")
    val publicAdministrationSocialSecurity: types.Sector.Value = Value("84")
    val administrationGeneral: types.Sector.Value = Value("84.1")
    val generalPublicAdmin: types.Sector.Value = Value("84.11")
    val healthEducationRegulation: types.Sector.Value = Value("84.12")
    val businessRegulation: types.Sector.Value = Value("84.13")
    val communityServices: types.Sector.Value = Value("84.2")
    val defence: types.Sector.Value = Value("84.22")
    val fireService: types.Sector.Value = Value("84.25")
    val foreignAffairs: types.Sector.Value = Value("84.21")
    val justiceJudicial: types.Sector.Value = Value("84.23")
    val publicOrderSafety: types.Sector.Value = Value("84.24")
    val compulsorySocialSecurity: types.Sector.Value = Value("84.3")
    val compulsorySocialSecurity4: types.Sector.Value = Value("84.30")

    val education: types.Sector.Value = Value("Q")
    val education2: types.Sector.Value = Value("85")
    val prePrimaryEducation: types.Sector.Value = Value("85.1")
    val prePrimaryEducation4: types.Sector.Value = Value("85.10")
    val primaryEducation: types.Sector.Value = Value("85.2")
    val primaryEducation4: types.Sector.Value = Value("85.20")
    val secondaryEducation: types.Sector.Value = Value("85.3")
    val generalSecondaryEducation: types.Sector.Value = Value("85.31")
    val vocationalSecondaryEducation: types.Sector.Value = Value("85.32")
    val postSecondaryEducationNonTertiary: types.Sector.Value = Value("85.33")
    val tertiaryEducation: types.Sector.Value = Value("85.4")
    val tertiaryEducation4: types.Sector.Value = Value("85.40")
    val otherEducation: types.Sector.Value = Value("85.5")
    val culturalEducation: types.Sector.Value = Value("85.52")
    val drivingSchool: types.Sector.Value = Value("85.53")
    val sportsRecreationEducation: types.Sector.Value = Value("85.51")
    val otherEducationNEC: types.Sector.Value = Value("85.59")
    val educationalSupport: types.Sector.Value = Value("85.6")
    val educationalSupportIntermediation: types.Sector.Value = Value("85.61")
    val otherEducationalSupport: types.Sector.Value = Value("85.69")

    val humanHealthSocialWork: types.Sector.Value = Value("R")
    val humanHealthActivities: types.Sector.Value = Value("86")
    val hospital: types.Sector.Value = Value("86.1")
    val hospitalActivities: types.Sector.Value = Value("86.10")
    val medicalDental: types.Sector.Value = Value("86.2")
    val dental: types.Sector.Value = Value("86.23")
    val generalPractice: types.Sector.Value = Value("86.21")
    val specialists: types.Sector.Value = Value("86.22")
    val otherHumanHealth: types.Sector.Value = Value("86.9")
    val psychologists: types.Sector.Value = Value("86.93")
    val diagnosticImaging: types.Sector.Value = Value("86.91")
    val nursingMidwifery: types.Sector.Value = Value("86.94")
    val ambulance: types.Sector.Value = Value("86.92")
    val physiotherapy: types.Sector.Value = Value("86.95")
    val traditionalMedicine: types.Sector.Value = Value("86.96")
    val humanHealthActivitiesIntermediationServices: types.Sector.Value = Value("86.97")
    val otherHumanHealthActivities4: types.Sector.Value = Value("86.99")

    val residentialCareActivities: types.Sector.Value = Value("87")
    val residentialNursing: types.Sector.Value = Value("87.1")
    val residentialNursing4: types.Sector.Value = Value("87.10")
    val residentialCareActivitiesMentalIllness: types.Sector.Value = Value("87.2")
    val residentialCareActivitiesMentalIllness4: types.Sector.Value = Value("87.20")
    val disabledResidentialCareActivitiesMentalIllness: types.Sector.Value = Value("87.3")
    val disabledResidentialCareActivitiesMentalIllness4: types.Sector.Value = Value("87.30")
    val otherResidentialCare: types.Sector.Value = Value("87.9")
    val otherResidentialCareIntermediation: types.Sector.Value = Value("87.91")
    val otherResidentialCare4: types.Sector.Value = Value("87.99")

    val otherSocialWork: types.Sector.Value = Value("88")
    val socialWorkDisabilities: types.Sector.Value = Value("88.1")
    val socialWorkDisabilities4: types.Sector.Value = Value("88.10")
    val otherSocialWorkWithoutAccommodation: types.Sector.Value = Value("88.9")
    val childDayCare: types.Sector.Value = Value("88.91")
    val otherSocialWorkNEC: types.Sector.Value = Value("88.99")

    val artsSportsRecreation: types.Sector.Value = Value("S")
    val artsCreationPerforming: types.Sector.Value = Value("90")
    val artsCreation: types.Sector.Value = Value("90.1")
    val literaryMusical: types.Sector.Value = Value("90.11")
    val visualArtsCreation: types.Sector.Value = Value("90.12")
    val otherArtsCreation: types.Sector.Value = Value("90.13")
    val performingArts: types.Sector.Value = Value("90.2")
    val performingArtsActivities: types.Sector.Value = Value("90.20")
    val performingArtsSupport: types.Sector.Value = Value("90.3")
    val artsFacilitiesOperation: types.Sector.Value = Value("90.31")
    val otherPerformingArtsSupport: types.Sector.Value = Value("90.39")

    val librariesArchivesMuseums: types.Sector.Value = Value("91")
    val libraryArchives: types.Sector.Value = Value("91.1")
    val archives: types.Sector.Value = Value("91.12")
    val libraries: types.Sector.Value = Value("91.11")
    val museumCollectionsMonuments: types.Sector.Value = Value("91.2")
    val historicalSitesMonuments: types.Sector.Value = Value("91.22")
    val museumsCollections: types.Sector.Value = Value("91.21")
    val culturalHeritageConservation: types.Sector.Value = Value("91.3")
    val culturalHeritageConservation4: types.Sector.Value = Value("91.30")
    val botanicalGardensAndNatureReserves: types.Sector.Value = Value("91.4")
    val botanicalZoologicalGardens: types.Sector.Value = Value("91.41")
    val natureReserves: types.Sector.Value = Value("91.42")

    val gamblingBetting: types.Sector.Value = Value("92")
    val gamblingActivities: types.Sector.Value = Value("92.0")
    val gamblingActivities4: types.Sector.Value = Value("92.00")

    val sportsAndRecreation: types.Sector.Value = Value("93")
    val sports: types.Sector.Value = Value("93.1")
    val fitnessCentresActivities: types.Sector.Value = Value("93.13")
    val sportsClubsActivities: types.Sector.Value = Value("93.12")
    val sportsFacilitiesOperation: types.Sector.Value = Value("93.11")
    val otherSportsActivities: types.Sector.Value = Value("93.19")
    val amusementRecreation: types.Sector.Value = Value("93.2")
    val amusementParks: types.Sector.Value = Value("93.21")
    val otherRecreationActivities: types.Sector.Value = Value("93.29")

    val otherService: types.Sector.Value = Value("T")
    val membershipOrganisations: types.Sector.Value = Value("94")
    val businessEmployersProfessional: types.Sector.Value = Value("94.1")
    val businessEmployersMembership: types.Sector.Value = Value("94.11")
    val professionalMembership: types.Sector.Value = Value("94.12")
    val tradeUnions: types.Sector.Value = Value("94.2")
    val tradeUnionsActivities: types.Sector.Value = Value("94.20")
    val otherMembership: types.Sector.Value = Value("94.9")
    val politicalOrganisations: types.Sector.Value = Value("94.92")
    val religiousOrganisations: types.Sector.Value = Value("94.91")
    val otherMembershipOrganisations: types.Sector.Value = Value("94.99")

    val repairMaintenance: types.Sector.Value = Value("95")
    val computerEquipment: types.Sector.Value = Value("95.1")
    val repairComputersCommunication: types.Sector.Value = Value("95.10")
    val repairHouseholdGoods: types.Sector.Value = Value("95.2")
    val repairConsumerElectronics: types.Sector.Value = Value("95.21")
    val repairFootwearLeather: types.Sector.Value = Value("95.23")
    val repairFurnitureHome: types.Sector.Value = Value("95.24")
    val repairHouseholdAppliances: types.Sector.Value = Value("95.22")
    val watchesAndJewellery: types.Sector.Value = Value("95.25")
    val otherHouseholdGoods: types.Sector.Value = Value("95.29")
    val repairMotorVehiclesMotorcycles: types.Sector.Value = Value("95.3")
    val repairMotorVehicles: types.Sector.Value = Value("95.31")
    val repairMotorcycles: types.Sector.Value = Value("95.32")
    val intermediationRepairMaintenance: types.Sector.Value = Value("95.4")
    val computerAndMotorcycleMaintenanceIntermediationServiceActivities4: types.Sector.Value = Value("95.40")

    val personalServices: types.Sector.Value = Value("96")
    val textileFurCleaning: types.Sector.Value = Value("96.1")
    val cleaningTextileProducts4: types.Sector.Value = Value("96.10")
    val beautyTreatment: types.Sector.Value = Value("96.2")
    val beautyCare: types.Sector.Value = Value("96.22")
    val spaActivities: types.Sector.Value = Value("96.23")
    val hairdressing: types.Sector.Value = Value("96.21")
    val funeralActivities: types.Sector.Value = Value("96.3")
    val funeralActivities4: types.Sector.Value = Value("96.30")
    val personalServicesIntermediation: types.Sector.Value = Value("96.4")
    val personalServicesIntermediation4: types.Sector.Value = Value("96.40")
    val otherPersonalServices: types.Sector.Value = Value("96.9")
    val domesticPersonalServices: types.Sector.Value = Value("96.91")
    val otherPersonalServices4: types.Sector.Value = Value("96.99")

    val households: types.Sector.Value = Value("U")
    val householdsActivitiesOfDomesticPersonnel: types.Sector.Value = Value("97")
    val householdsActivitiesOfDomesticPersonnel3: types.Sector.Value = Value("97.0")
    val domesticPersonnel: types.Sector.Value = Value("97.00")
    val undifferentiatedGoodsAndServiceActivities: types.Sector.Value = Value("98")
    val undifferentiatedGoods: types.Sector.Value = Value("98.1")
    val undifferentiatedGoods4: types.Sector.Value = Value("98.10")
    val undifferentiatedServices: types.Sector.Value = Value("98.2")
    val undifferentiatedProduction: types.Sector.Value = Value("98.20")

    val activitiesExtraterritorial: types.Sector.Value = Value("V")
    val extraterritorialOrganisationsActivities: types.Sector.Value = Value("99")
    val extraterritorialOrganisationsActivities3: types.Sector.Value = Value("99.0")
    val extraterritorialOrganisationsActivities4: types.Sector.Value = Value("99.00")

    implicit val format: Format[Sector] = Json.formatEnum(Sector)
  }
  object UndertakingStatus extends Enumeration {
    type UndertakingStatus = Value
    val active: types.UndertakingStatus.Value = Value(0)
    val suspendedAutomated: types.UndertakingStatus.Value = Value(1)
    val suspendedManual: types.UndertakingStatus.Value = Value(5)
    val suspendedUndertaking: types.UndertakingStatus.Value = Value(8)
    val inactive: types.UndertakingStatus.Value = Value(9)
    implicit val format: Format[UndertakingStatus] = Json.formatEnum(UndertakingStatus)
  }

  type SubsidyRef = String @@ SubsidyRef.Tag
  object SubsidyRef
      extends RegexValidatedString(
        "^[A-Za-z0-9]{1,10}$" // n.b. no longer exact match for spec which accepts n of any char
      )

  type EisSubsidyAmendmentType = String @@ EisSubsidyAmendmentType.Tag
  object EisSubsidyAmendmentType
      extends RegexValidatedString(
        regex = "1|2|3"
      )

  object AmendmentType extends Enumeration {
    type AmendmentType = Value

    val add: types.AmendmentType.Value = Value("1")
    val amend: types.AmendmentType.Value = Value("2")
    val delete: types.AmendmentType.Value = Value("3")

    implicit val format: Format[AmendmentType] = Json.formatEnum(AmendmentType)

  }

  type ErrorMessage = String @@ ErrorMessage.Tag
  object ErrorMessage
      extends RegexValidatedString(
        """.{1,255}"""
      )

  object EmailStatus extends Enumeration {
    type EmailStatus = Value
    val Unverified: types.EmailStatus.Value = Value("unverified")
    val New: types.EmailStatus.Value = Value("new")
    val Amend: types.EmailStatus.Value = Value("amend")
    val BecomeLead: types.EmailStatus.Value = Value("become-lead")
    val CYA: types.EmailStatus.Value = Value("cya")

    implicit val format: Format[EmailStatus] = Json.formatEnum(EmailStatus)

    implicit object Binder extends PathBindable[EmailStatus] {

      override def bind(key: String, value: String): Either[String, EmailStatus] =
        Try(EmailStatus.withName(value)).toOption
          .map(Right(_))
          .getOrElse(Left("Cannot parse parameter '" + key + "' as EmailStatus"))

      override def unbind(key: String, value: EmailStatus): String = value.toString

    }

    implicit val queryStringBindable: QueryStringBindable[EmailStatus] =
      new QueryStringBindable[EmailStatus] {
        override def bind(
          key: String,
          params: Map[String, Seq[String]]
        ): Option[Either[String, EmailStatus]] =
          params.get(key).collect { case Seq(s) =>
            EmailStatus.values.find(_.toString == s).toRight("invalid sort field parameter")
          }

        override def unbind(key: String, value: EmailStatus): String =
          implicitly[QueryStringBindable[String]].unbind(key, value.toString)
      }
  }

  object VerifiedStatus extends Enumeration {
    type VerifiedStatus = Value
    val Verified: types.VerifiedStatus.Value = Value("verified")

    implicit val format: Format[VerifiedStatus] = Json.formatEnum(VerifiedStatus)
  }

}
