/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.eusubsidycompliancefrontend.models

import play.api.libs.json.{Format, Json}
import play.api.mvc.{PathBindable, QueryStringBindable}
import shapeless.tag.@@

import scala.util.Try

package object types extends SimpleJson {

  val MaxInputValue = 99999999999.99

  type IndustrySectorLimit = BigDecimal @@ IndustrySectorLimit.Tag
  object IndustrySectorLimit extends ValidatedType[BigDecimal] {
    override def validateAndTransform(in: BigDecimal): Option[BigDecimal] =
      Some(in).filter { x =>
        (x <= MaxInputValue) && (x.scale <= 2)
      }
  }

  type PositiveSubsidyAmount = BigDecimal @@ PositiveSubsidyAmount.Tag
  object PositiveSubsidyAmount extends ValidatedType[BigDecimal] {
    override def validateAndTransform(in: BigDecimal): Option[BigDecimal] =
      Some(in).filter { x =>
        (x >= 0) && (x <= MaxInputValue) && (x.scale <= 2)
      }
  }

  type SubsidyAmount = BigDecimal @@ SubsidyAmount.Tag
  object SubsidyAmount extends ValidatedType[BigDecimal] {
    override def validateAndTransform(in: BigDecimal): Option[BigDecimal] =
      Some(in).filter { x =>
        (x >= -MaxInputValue) && (x <= MaxInputValue) && (x.scale <= 2)
      }
    val Zero: SubsidyAmount = SubsidyAmount(BigDecimal(0))
  }

  type DeclarationID = String @@ DeclarationID.Tag
  object DeclarationID
      extends RegexValidatedString(
        regex = """.{1,18}"""
      )

  type TaxType = String @@ TaxType.Tag
  object TaxType
      extends RegexValidatedString(
        regex = """.{0,3}"""
      )

  type TraderRef = String @@ TraderRef.Tag
  object TraderRef
      extends RegexValidatedString(
        regex = """[A-Za-z0-9\W_ ]{1,400}""" //dev agreed setting an arbitary limit of 400
      )

  type UndertakingName = String @@ UndertakingName.Tag
  object UndertakingName
      extends RegexValidatedString(
        regex = """.{1,105}"""
      )

  type EORI = String @@ EORI.Tag
  object EORI
      extends RegexValidatedString(
        """^(gb|Gb|gB|GB|XI)[0-9]{12,15}$"""
      ) {

    val ValidLengthsWithPrefix = Set(14, 17) // Valid lengths with 2 letter prefix

    def withGbPrefix(eori: String): String =
      if (eori.startsWith("GB")) eori
      else s"GB$eori"

    def formatEori(eori: String): String = {
      val s = eori.replaceAll(" ", "")
      s.take(2).toUpperCase + s.drop(2)
    }
  }

  type UndertakingRef = String @@ UndertakingRef.Tag
  object UndertakingRef
      extends RegexValidatedString(
        regex = """[A-Za-z0-9]{1,17}""" // n.b. no longer exact match for spec which accepts n of any char
      )

  object Sector extends Enumeration {
    type Sector = Value
    val other: types.Sector.Value = Value("0")
    val transport: types.Sector.Value = Value("1")
    val agriculture: types.Sector.Value = Value("2")
    val aquaculture: types.Sector.Value = Value("3")

    val agricultureForestryFishing: types.Sector.Value = Value("A")
    val cropAnimalProduction: types.Sector.Value = Value("01")
      val growingNonPerennialCrops: types.Sector.Value = Value("01.1")
        val	cerealsLeguminousCrops: types.Sector.Value = Value("01.11")
        val	fibreCrops: types.Sector.Value = Value("01.16")
        val	rice: types.Sector.Value = Value("01.12")
        val	sugarCane: types.Sector.Value = Value("01.14")
        val	tobacco: types.Sector.Value = Value("01.15")
        val	vegetables: types.Sector.Value = Value("01.13")
        val otherNonPerennialCrops: types.Sector.Value = Value("01.19")
    val	growingPerennialCrops: types.Sector.Value = Value("01.2")
      val	beverageCrops: types.Sector.Value = Value("01.27")
      val	citrusFruits: types.Sector.Value = Value("01.23")
      val	grapes: types.Sector.Value = Value("01.21")
      val	oleaginousFruits: types.Sector.Value = Value("01.26")
      val	stoneFruits: types.Sector.Value = Value("01.24")
      val	spicesPharmaceuticalCrops: types.Sector.Value = Value("01.28")
      val	tropicalFruits: types.Sector.Value = Value("01.22")
      val	otherTree: types.Sector.Value = Value("01.25")
      val otherPerennialCrops	: types.Sector.Value = Value("01.29")
    val	plantPropagation: types.Sector.Value = Value("01.3")
      val plantPropagation4	: types.Sector.Value = Value("01.30")
      val	animalProduction: types.Sector.Value = Value("01.4")
      val	dairyCattle: types.Sector.Value = Value("01.41")
      val	otherCattle: types.Sector.Value = Value("01.42")
      val	camels: types.Sector.Value = Value("01.44")
      val	horses: types.Sector.Value = Value("01.43")
      val	poultry: types.Sector.Value = Value("01.47")
      val	sheep: types.Sector.Value = Value("01.45")
      val	swine: types.Sector.Value = Value("01.46")
      val	otherAnimals: types.Sector.Value = Value("01.48")
    val mixedFarming	: types.Sector.Value = Value("01.5")
      val	mixedFarming4: types.Sector.Value = Value("01.50")
    val supportActivities: types.Sector.Value = Value("01.6")
      val	postHarvestActivities: types.Sector.Value = Value("01.63")
      val	supportActivitiesAnimal: types.Sector.Value = Value("01.62")
      val	supportActivitiesCrop: types.Sector.Value = Value("01.61")
    val huntingTrapping	: types.Sector.Value = Value("01.7")
      val	huntingTrapping4: types.Sector.Value = Value("01.70")

    val forestry : types.Sector.Value = Value("02")
    val silviculture : types.Sector.Value = Value("02.1")
    val silviculture4 : types.Sector.Value = Value("02.10")
    val logging	: types.Sector.Value = Value("02.2")
    val logging4: types.Sector.Value = Value("02.20")
    val gatheringOfWildGrowth : types.Sector.Value = Value("02.3")
    val gatheringOfWildGrowth4: types.Sector.Value = Value("02.30")
    val forestrySupportServices: types.Sector.Value = Value("02.4")
    val forestrySupportServices4: types.Sector.Value = Value("02.40")

    val fishingAndAquaculture: types.Sector.Value = Value("03")
      val fishing: types.Sector.Value = Value("03.1")
        val freshwaterFishing: types.Sector.Value = Value("03.12")
        val marineFishing: types.Sector.Value = Value("03.11")
      val aquaculture3: types.Sector.Value = Value("03.2")
        val freshwaterAquaculture: types.Sector.Value = Value("03.22")
        val marineAquaculture: types.Sector.Value = Value("03.21")
      val aquacultureSupportActivities: types.Sector.Value = Value("03.3")
        val aquacultureSupportActivities4: types.Sector.Value = Value("03.30")

   val miningQuarrying : types.Sector.Value = Value("B")
   val coalAndLigniteMining : types.Sector.Value = Value("05")
   val hardcoal: types.Sector.Value = Value("05.1")
   val hardcoalMining: types.Sector.Value = Value("05.10")
   val lignite: types.Sector.Value = Value("05.2")
   val ligniteMining: types.Sector.Value = Value("05.20")
   val petroleumNaturalGasExtraction : types.Sector.Value = Value("06")
   val crudePetroleum: types.Sector.Value = Value("06.1")
   val crudePetroleumExtraction: types.Sector.Value = Value("06.10")
   val naturalGas: types.Sector.Value = Value("06.2")
   val naturalGasExtraction : types.Sector.Value = Value("06.20")
   val metalOresMining: types.Sector.Value = Value("07")
   val ironOre: types.Sector.Value = Value("07.1")
   val ironOresMining: types.Sector.Value = Value("07.10")
   val nonFerrousOres: types.Sector.Value = Value("07.2")
   val uraniumThoriumOres: types.Sector.Value = Value("07.21")
   val otherNonFerrousOres: types.Sector.Value = Value("07.29")
   val otherMiningQuarrying: types.Sector.Value = Value("08")
   val stoneQuarrying : types.Sector.Value = Value("08.1")
   val gravelPitsOperation: types.Sector.Value = Value("08.12")
   val ornamentalQuarrying: types.Sector.Value = Value("08.11")
   val miningAndQuarryingNEC: types.Sector.Value = Value("08.9")
   val peatExtraction : types.Sector.Value = Value("08.92")
   val saltExtraction: types.Sector.Value = Value("08.93")
   val chemicalMineralsMining : types.Sector.Value = Value("08.91")
   val otherNEC: types.Sector.Value = Value("08.99")
   val miningSupportServices: types.Sector.Value = Value("09")
   val miningSupportPetroleumExtraction: types.Sector.Value = Value("09.1")
   val miningSupportPetroleumExtraction4: types.Sector.Value = Value("09.10")
   val otherMiningSupport : types.Sector.Value = Value("09.9")
   val otherMiningSupport4: types.Sector.Value = Value("09.90")

    val Manufacturing: types.Sector.Value = Value("C")
    val Food: types.Sector.Value = Value("10")
    val Meat: types.Sector.Value = Value("10.1")
    val meatProcessing: types.Sector.Value = Value("10.11")
    val poultryProcessing: types.Sector.Value = Value("10.12")
    val meatProductsProduction: types.Sector.Value = Value("10.13")
    val Fish: types.Sector.Value = Value("10.2")
    val fishProcessing: types.Sector.Value = Value("10.20")
    val FruitAndVegetables: types.Sector.Value = Value("10.3")
    val FruitAndVegetableJuiceManufacture: types.Sector.Value = Value("10.32")
    val FruitAndVegetableProcessing: types.Sector.Value = Value("10.31")
    val OtherFruitAndVegetableProcessing: types.Sector.Value = Value("10.39")
    val Oils: types.Sector.Value = Value("10.4")
    val Margarine: types.Sector.Value = Value("10.42")
    val OtherOils: types.Sector.Value = Value("10.41")
    val DairyProducts: types.Sector.Value = Value("10.5")
    val DairyProducts4: types.Sector.Value = Value("10.51")
    val IceCream: types.Sector.Value = Value("10.52")
    val GrainAndStarchProducts: types.Sector.Value = Value("10.6")
    val GrainProducts4: types.Sector.Value = Value("10.61")
    val starchProducts: types.Sector.Value = Value("10.62")
    val BakeryProducts: types.Sector.Value = Value("10.7")
    val BiscuitsAndPreservedCakes: types.Sector.Value = Value("10.72")
    val BreadAndFreshPastry: types.Sector.Value = Value("10.71")
    val FarinaceousProducts: types.Sector.Value = Value("10.73")
    val OtherFoodProducts	: types.Sector.Value = Value("10.8")
    val confectionery: types.Sector.Value = Value("10.82")
    val Condiments: types.Sector.Value = Value("10.84")
    val HomogenisedFoodPreparations: types.Sector.Value = Value("10.86")
    val PreparedMeals: types.Sector.Value = Value("10.85")
    val Sugar: types.Sector.Value = Value("10.81")
    val TeaAndCoffee: types.Sector.Value = Value("10.83")
    val otherFoodProduct: types.Sector.Value = Value("10.89")
    val PreparedAnimalFeeds	: types.Sector.Value = Value("10.9")
    val farmAnimalsFood : types.Sector.Value = Value("10.91")
    val PetFood: types.Sector.Value = Value("10.92")

    val Beverages: types.Sector.Value = Value("11")
    val BeverageManufacture: types.Sector.Value = Value("11.0")
    val beer: types.Sector.Value = Value("11.05")
    val ciders: types.Sector.Value = Value("11.03")
    val malt: types.Sector.Value = Value("11.06")
    val SoftDrinks: types.Sector.Value = Value("11.07")
    val Spirits: types.Sector.Value = Value("11.01")
    val Wine: types.Sector.Value = Value("11.02")
    val OtherFermentedBeverages: types.Sector.Value = Value("11.04")

    val TobaccoProducts: types.Sector.Value = Value("12")
    val TobaccoProductsManufacture3: types.Sector.Value = Value("12.0")
    val TobaccoProductsManufacture4: types.Sector.Value = Value("12.00")

    val Textiles: types.Sector.Value = Value("13")
    val textilesPreparation : types.Sector.Value = Value("13.1")
    val textilesPreparation4: types.Sector.Value = Value("13.10")
    val textilesWeaving	: types.Sector.Value = Value("13.2")
    val textilesWeaving4: types.Sector.Value = Value("13.20")
    val textilesFinishing : types.Sector.Value = Value("13.3")
    val textilesFinishing4: types.Sector.Value = Value("13.30")
    val textilesManufacture: types.Sector.Value = Value("13.9")
    val Carpets: types.Sector.Value = Value("13.93")
    val Cordage: types.Sector.Value = Value("13.94")
    val householdTextiles : types.Sector.Value = Value("13.92")
    val KnittedFabrics: types.Sector.Value = Value("13.91")
    val NonWoven: types.Sector.Value = Value("13.95")
    val OtherTechnicalTextiles: types.Sector.Value = Value("13.96")
    val otherTextile: types.Sector.Value = Value("13.99")

    val Clothing: types.Sector.Value = Value("14")
    val KnittedCrotchetedClothing	: types.Sector.Value = Value("14.1")
    val KnittedClothingManufacture : types.Sector.Value = Value("14.10")
    val OtherClothing: types.Sector.Value = Value("14.2")
    val LeatherAndFurClothing: types.Sector.Value = Value("14.24")
    val Outerwear: types.Sector.Value = Value("14.21")
    val Underwear: types.Sector.Value = Value("14.22")
    val Workwear: types.Sector.Value = Value("14.23")
    val OtherClothing4: types.Sector.Value = Value("14.29")

    val LeatherProducts	: types.Sector.Value = Value("15")
    val LeatherManufacture: types.Sector.Value = Value("15.1")
    val luggageManufacture : types.Sector.Value = Value("15.12")
    val LeatherTanning: types.Sector.Value = Value("15.11")
    val footwearManufacture: types.Sector.Value = Value("15.2")
    val footwearManufacture4: types.Sector.Value = Value("15.20")

    val WoodProducts: types.Sector.Value = Value("16")
    val WoodProductsProcessing: types.Sector.Value = Value("16.1")
    val ProcessingAndFinishing: types.Sector.Value = Value("16.12")
    val SawmillingAndPlaning: types.Sector.Value = Value("16.11")
    val WoodProductsManufacture: types.Sector.Value = Value("16.2")
    val AssembledParquetFloors: types.Sector.Value = Value("16.22")
    val SolidFuelsVegetableBiomass: types.Sector.Value = Value("16.26")
    val VeneerSheetsPanels: types.Sector.Value = Value("16.21")
    val WoodenContainers: types.Sector.Value = Value("16.24")
    val WoodenWindowsDoors: types.Sector.Value = Value("16.25")
    val OtherBuildersCarpentryJoinery: types.Sector.Value = Value("16.23")
    val OtherWoodProducts: types.Sector.Value = Value("16.28")
    val woodenProductsFinishing: types.Sector.Value = Value("16.27")

    val PaperRelated: types.Sector.Value = Value("17")
    val Pulp: types.Sector.Value = Value("17.1")
    val Pulp4: types.Sector.Value = Value("17.11")
    val Paper: types.Sector.Value = Value("17.12")
    val ArticlesPaperBoard	: types.Sector.Value = Value("17.2")
    val CorrugatedPaperBoardAndContainers: types.Sector.Value = Value("17.21")
    val SanitaryGoods: types.Sector.Value = Value("17.22")
    val PaperStationery: types.Sector.Value = Value("17.23")
    val Wallpaper: types.Sector.Value = Value("17.24")
    val OtherPaper: types.Sector.Value = Value("17.25")

    val PrintedProducts: types.Sector.Value = Value("18")
    val PrintingService : types.Sector.Value = Value("18.1")
    val BindingServices: types.Sector.Value = Value("18.14")
    val PreMediaServices: types.Sector.Value = Value("18.13")
    val NewspapersPrinting : types.Sector.Value = Value("18.11")
    val OtherPrinting: types.Sector.Value = Value("18.12")
    val RecordedMediaReproduction: types.Sector.Value = Value("18.2")
    val RecordedMediaReproduction4: types.Sector.Value = Value("18.20")

    val CokeProducts: types.Sector.Value = Value("19")
    val OvenCokeProducts : types.Sector.Value = Value("19.1")
    val CokeProductsManufacture: types.Sector.Value = Value("19.10")
    val FossilFuelProducts: types.Sector.Value = Value("19.2")
    val FossilFuelProductsManufacture: types.Sector.Value = Value("19.20")

    val ChemicalProducts: types.Sector.Value = Value("20")
    val BasicChemicalProducts: types.Sector.Value = Value("20.1")
    val Dyes: types.Sector.Value = Value("20.12")
    val Fertilisers: types.Sector.Value = Value("20.15")
    val IndustrialGases: types.Sector.Value = Value("20.11")
    val PrimaryFormsPlastics: types.Sector.Value = Value("20.16")
    val SyntheticRubber : types.Sector.Value = Value("20.17")
    val OtherInorganicChemicals: types.Sector.Value = Value("20.13")
    val OtherOrganicChemicals: types.Sector.Value = Value("20.14")
    val PesticidesDisinfectants: types.Sector.Value = Value("20.2")
    val PesticidesDisinfectantsManufacture : types.Sector.Value = Value("20.20")
    val PaintsVarnishesCoatings: types.Sector.Value = Value("20.3")
    val PaintsVarnishesCoatingsManufacture : types.Sector.Value = Value("20.30")
    val WashingCleaning : types.Sector.Value = Value("20.4")
    val PerfumesToiletPreparations: types.Sector.Value = Value("20.42")
    val Soap: types.Sector.Value = Value("20.41")
    val OtherChemicalProducts: types.Sector.Value = Value("20.5")
    val LiquidBiofuels: types.Sector.Value = Value("20.51")
    val OtherChemicalProducts4: types.Sector.Value = Value("20.59")
    val ManMadeFibre: types.Sector.Value = Value("20.6")
    val ManMadeFibreManufacture: types.Sector.Value = Value("20.60")

    val Pharmaceuticals: types.Sector.Value = Value("21")
    val BasicPharmaceuticals: types.Sector.Value = Value("21.1")
    val PharmaceuticalsManufacture: types.Sector.Value = Value("21.10")
    val PharmaceuticalPreparations: types.Sector.Value = Value("21.2")
    val PharmaceuticalPreparationsManufacture: types.Sector.Value = Value("21.20")

    val RubberPlasticProducts: types.Sector.Value = Value("22")
    val RubberProducts: types.Sector.Value = Value("22.1")
    val RubberTubes: types.Sector.Value = Value("22.11")
    val OtherRubberProducts: types.Sector.Value = Value("22.12")
    val PlasticProducts: types.Sector.Value = Value("22.2")
    val BuildersWare: types.Sector.Value = Value("22.24")
    val DoorsAndWindows: types.Sector.Value = Value("22.23")
    val PackingGoods: types.Sector.Value = Value("22.22")
    val PlasticPlatesSheetsTubes: types.Sector.Value = Value("22.21")
    val OtherPlasticProduct: types.Sector.Value = Value("22.26")
    val FinishingPlasticProducts: types.Sector.Value = Value("22.25")

    val OtherNonMetallicProducts: types.Sector.Value = Value("23")
    val GlassProducts: types.Sector.Value = Value("23.1")
    val FlatGlass: types.Sector.Value = Value("23.11")
    val GlassFibres: types.Sector.Value = Value("23.14")
    val HollowGlass: types.Sector.Value = Value("23.13")
    val OtherGlassProducts: types.Sector.Value = Value("23.15")
    val ShapingFlatGlass: types.Sector.Value = Value("23.12")
    val RefractoryProducts: types.Sector.Value = Value("23.2")
    val RefractoryProductsManufacture : types.Sector.Value = Value("23.20")
    val ClayBuildingMaterials	: types.Sector.Value = Value("23.3")
    val Bricks: types.Sector.Value = Value("23.32")
    val CeramicTiles: types.Sector.Value = Value("23.31")
    val OtherCeramicProducts	: types.Sector.Value = Value("23.4")
    val CeramicHousehold: types.Sector.Value = Value("23.41")
    val CeramicInsulating : types.Sector.Value = Value("23.43")
    val CeramicSanitary: types.Sector.Value = Value("23.42")
    val OtherTechnicalCeramicProducts: types.Sector.Value = Value("23.44")
    val OtherCeramicProducts4: types.Sector.Value = Value("23.45")
    val CementLimePlaster: types.Sector.Value = Value("23.5")
    val Cement: types.Sector.Value = Value("23.51")
    val PlasterLime: types.Sector.Value = Value("23.52")
    val CementPlasterArticles : types.Sector.Value = Value("23.6")
    val ConcreteProducts: types.Sector.Value = Value("23.61")
    val FibreCement: types.Sector.Value = Value("23.65")
    val Mortars: types.Sector.Value = Value("23.64")
    val PlasterProducts : types.Sector.Value = Value("23.62")
    val ReadyMixedConcrete: types.Sector.Value = Value("23.63")
    val OtherConcreteProducts: types.Sector.Value = Value("23.66")
    val StoneCuttingFinishing	: types.Sector.Value = Value("23.7")
    val StoneCuttingFinishing4: types.Sector.Value = Value("23.70")
    val OtherAbrasiveProducts: types.Sector.Value = Value("23.9")
    val AbrasiveProducts: types.Sector.Value = Value("23.91")
    val OtherNonMetallicMineral: types.Sector.Value = Value("23.99")

    val BasicMetals: types.Sector.Value = Value("24")
    val BasicIronSteel: types.Sector.Value = Value("24.1")
    val BasicIronSteelManufacture: types.Sector.Value = Value("24.10")
    val SteelTubesFittings: types.Sector.Value = Value("24.2")
    val SteelTubesFittingsManufacture : types.Sector.Value = Value("24.20")
    val OtherSteelProductsProcessing: types.Sector.Value = Value("24.3")
    val BarsColdDrawing: types.Sector.Value = Value("24.31")
    val WireColdDrawing: types.Sector.Value = Value("24.34")
    val FoldingColdDrawing: types.Sector.Value = Value("24.33")
    val NarrowStripColdDrawing: types.Sector.Value = Value("24.32")
    val BasicPreciousAndNonFerrousMetals: types.Sector.Value = Value("24.4")
    val NuclearFuelProcessing : types.Sector.Value = Value("24.46")
    val AluminiumProduction : types.Sector.Value = Value("24.42")
    val CopperProduction : types.Sector.Value = Value("24.44")
    val LeadZincTinProduction: types.Sector.Value = Value("24.43")
    val PreciousMetalsProduction : types.Sector.Value = Value("24.41")
    val MonFerrousMetalsProduction: types.Sector.Value = Value("24.45")
    val MetalsCasting: types.Sector.Value = Value("24.5")
    val Iron: types.Sector.Value = Value("24.51")
    val LightMetals: types.Sector.Value = Value("24.53")
    val Steel: types.Sector.Value = Value("24.52")
    val OtherMetals: types.Sector.Value = Value("24.54")

    val FabricatedMetalProducts: types.Sector.Value = Value("25")
    val FabricatedStructuralMetalProducts: types.Sector.Value = Value("25.1")
    val MetalDoors: types.Sector.Value = Value("25.12")
    val MetalStructures: types.Sector.Value = Value("25.11")
    val MetalTanksManufacture: types.Sector.Value = Value("25.2")
    val CentralHeating: types.Sector.Value = Value("25.21")
    val OtherMetalTanks: types.Sector.Value = Value("25.22")
    val WeaponsManufacture : types.Sector.Value = Value("25.3")
    val WeaponsManufacture4: types.Sector.Value = Value("25.30")
    val MetalForging: types.Sector.Value = Value("25.4")
    val MetalForging4: types.Sector.Value = Value("25.40")
    val MetalTreatmentCoating: types.Sector.Value = Value("25.5")
    val Coating: types.Sector.Value = Value("25.51")
    val HeatTreatment: types.Sector.Value = Value("25.52")
    val Machining: types.Sector.Value = Value("25.53")
    val CutleryToolsManufacture: types.Sector.Value = Value("25.6")
    val Cutlery: types.Sector.Value = Value("25.61")
    val Locks: types.Sector.Value = Value("25.62")
    val Tools: types.Sector.Value = Value("25.63")
    val OtherFabricatedMetalProductsManufacture: types.Sector.Value = Value("25.9")
    val FastenerProducts: types.Sector.Value = Value("25.94")
    val LightMetalPackaging: types.Sector.Value = Value("25.92")
    val SteelDrums: types.Sector.Value = Value("25.91")
    val WireProducts: types.Sector.Value = Value("25.93")
    val OtherFabricatedMetalProducts: types.Sector.Value = Value("25.99")

    val ComputersProducts: types.Sector.Value = Value("26")
    val ElectronicComponents: types.Sector.Value = Value("26.1")
    val ElectronicComponents4: types.Sector.Value = Value("26.11")
    val LoadedElectronicBoards: types.Sector.Value = Value("26.12")
    val ComputersPeripheralEquipment: types.Sector.Value = Value("26.2")
    val ComputersPeripheralEquipment4: types.Sector.Value = Value("26.20")
    val CommunicationEquipment: types.Sector.Value = Value("26.3")
    val CommunicationEquipment4 : types.Sector.Value = Value("26.30")
    val ConsumerElectronics: types.Sector.Value = Value("26.4")
    val ConsumerElectronics4 : types.Sector.Value = Value("26.40")
    val MeasuringToolsAndClocks	: types.Sector.Value = Value("26.5")
    val MeasuringInstruments: types.Sector.Value = Value("26.51")
    val WatchesAndClocks: types.Sector.Value = Value("26.52")
    val IrradiationElectromedicalAndElectrotherapeuticEquipment	: types.Sector.Value = Value("26.6")
    val IrradiationElectromedicalAndElectrotherapeuticEquipment4: types.Sector.Value = Value("26.60")
    val OpticalEquipment: types.Sector.Value = Value("26.7")
    val OpticalEquipment4: types.Sector.Value = Value("26.70")

    val ElectricalEquipment	: types.Sector.Value = Value("27")
    val ElectricMotorsGenerators: types.Sector.Value = Value("27.1")
    val ElectricMotors: types.Sector.Value = Value("27.11")
    val ElectricityDistributionAndControl : types.Sector.Value = Value("27.12")
    val Batteries: types.Sector.Value = Value("27.2")
    val BatteriesManufacture: types.Sector.Value = Value("27.20")
    val Wiring: types.Sector.Value = Value("27.3")
    val FibreOpticCables: types.Sector.Value = Value("27.31")
    val OtherElectronicWires: types.Sector.Value = Value("27.32")
    val WiringDevices: types.Sector.Value = Value("27.33")
    val LightingEquipment: types.Sector.Value = Value("27.4")
    val LightingEquipmentManufacture: types.Sector.Value = Value("27.40")
    val DomesticAppliances: types.Sector.Value = Value("27.5")
    val ElectricDomesticAppliances: types.Sector.Value = Value("27.51")
    val NonElectricDomesticAppliances: types.Sector.Value = Value("27.52")
    val OtherElectricalEquipment: types.Sector.Value = Value("27.9")
    val OtherElectricalEquipmentManufacture: types.Sector.Value = Value("27.90")

    val OtherMachineryAndEquipment: types.Sector.Value = Value("28")
    val GeneralPurposeMachinery	: types.Sector.Value = Value("28.1")
    val Bearings: types.Sector.Value = Value("28.15")
    val Engines: types.Sector.Value = Value("28.11")
    val FluidPowerEquipment: types.Sector.Value = Value("28.12")
    val OtherPumps: types.Sector.Value = Value("28.13")
    val OtherTaps : types.Sector.Value = Value("28.14")
    val OtherGeneralPurposeMachinery	: types.Sector.Value = Value("28.2")
    val LiftingEquipment: types.Sector.Value = Value("28.22")
    val NonDomesticAirConditioning: types.Sector.Value = Value("28.25")
    val OfficeMachinery: types.Sector.Value = Value("28.23")
    val Ovens: types.Sector.Value = Value("28.21")
    val PowerDrivenHandTools: types.Sector.Value = Value("28.24")
    val OtherGeneralPurposeMachinery4: types.Sector.Value = Value("28.29")
    val AgriculturalMachinery	: types.Sector.Value = Value("28.3")
    val AgriculturalMachineryManufacture : types.Sector.Value = Value("28.30")
    val MetalFormingMachinery 	: types.Sector.Value = Value("28.4")
    val MetalFormingMachinery4 : types.Sector.Value = Value("28.41")
    val OtherMachineTools: types.Sector.Value = Value("28.42")
    val OtherSpecialPurposeMachinery	: types.Sector.Value = Value("28.9")
    val AdditiveManufacturingMachinery: types.Sector.Value = Value("28.97")
    val foodMachinery : types.Sector.Value = Value("28.93")
    val metallurgyMachinery : types.Sector.Value = Value("28.91")
    val miningMachinery : types.Sector.Value = Value("28.92")
    val paperMachinery : types.Sector.Value = Value("28.95")
    val textileMachinery: types.Sector.Value = Value("28.94")
    val PlasticsMachinery: types.Sector.Value = Value("28.96")
    val OtherSpecialPurposeMachinery4: types.Sector.Value = Value("28.99")

    val MotorVehicles: types.Sector.Value = Value("29")
    val motorVehicles3	: types.Sector.Value = Value("29.1")
    val MotorVehiclesManufacture: types.Sector.Value = Value("29.10")
    val motorVehiclesBodies	: types.Sector.Value = Value("29.2")
    val MotorVehiclesBodies4: types.Sector.Value = Value("29.20")
    val motorVehiclesParts: types.Sector.Value = Value("29.3")
    val MotorVehiclesElectricalManufacture: types.Sector.Value = Value("29.31")
    val MotorVehiclesOtherManufacture: types.Sector.Value = Value("29.32")

    val OtherTransportEquipment: types.Sector.Value = Value("30")
    val Ships: types.Sector.Value = Value("30.1")
    val CivilianShips: types.Sector.Value = Value("30.11")
    val MilitaryShips: types.Sector.Value = Value("30.13")
    val PleasureShips: types.Sector.Value = Value("30.12")
    val Railway: types.Sector.Value = Value("30.2")
    val RailwayManufacture: types.Sector.Value = Value("30.20")
    val Aircraft: types.Sector.Value = Value("30.3")
    val CivilianAircraftMachinery: types.Sector.Value = Value("30.31")
    val MilitaryAircraftMachinery: types.Sector.Value = Value("30.32")
    val MilitaryFightingVehicles	: types.Sector.Value = Value("30.4")
    val MilitaryFightingVehiclesManufacture : types.Sector.Value = Value("30.40")
    val OtherTransportEquipment3	: types.Sector.Value = Value("30.9")
    val Bicycles : types.Sector.Value = Value("30.92")
    val MotorcyclesEquipment: types.Sector.Value = Value("30.91")
    val OtherTransportEquipment4: types.Sector.Value = Value("30.99")

    val FurnitureManufacture: types.Sector.Value = Value("31")
    val FurnitureManufacture3: types.Sector.Value = Value("31.0")
    val FurnitureManufacture4 : types.Sector.Value = Value("31.00")

    val OtherManufacturing: types.Sector.Value = Value("32")
    val JewelleryAndCoins: types.Sector.Value = Value("32.1")
    val JewelleryManufacture: types.Sector.Value = Value("32.12")
    val imitationJewelleryManufacture: types.Sector.Value = Value("32.13")
    val coinStriking : types.Sector.Value = Value("32.11")
    val MusicalInstruments: types.Sector.Value = Value("32.2")
    val MusicalInstrumentsManufacture : types.Sector.Value = Value("32.20")
    val SportsGoods: types.Sector.Value = Value("32.3")
    val SportsGoodsManufacture: types.Sector.Value = Value("32.30")
    val GamesAndToys: types.Sector.Value = Value("32.4")
    val GamesAndToysManufacture: types.Sector.Value = Value("32.40")
    val MedicalInstruments : types.Sector.Value = Value("32.5")
    val MedicalInstrumentsManufacture: types.Sector.Value = Value("32.50")
    val OtherProducts: types.Sector.Value = Value("32.9")
    val BroomsAndBrushes: types.Sector.Value = Value("32.91")
    val OtherProductManufacture: types.Sector.Value = Value("32.99")

    val MetalProductsRepairMaintenance: types.Sector.Value = Value("33")
    val fabricatedMetalProductsRepair: types.Sector.Value = Value("33.1")
    val CivilianAirRepair: types.Sector.Value = Value("33.16")
    val CivilianShipsRepair: types.Sector.Value = Value("33.15")
    val OtherCivilianTransportEquipmentRepair: types.Sector.Value = Value("33.17")
    val ElectricalEquipmentRepair: types.Sector.Value = Value("33.14")
    val opticalEquipmentRepair: types.Sector.Value = Value("33.13")
    val FabricatedMetalProductsRepair: types.Sector.Value = Value("33.11")
    val MachineryRepair: types.Sector.Value = Value("33.12")
    val MilitaryVehiclesRepair: types.Sector.Value = Value("33.18")
    val OtherEquipmentRepair: types.Sector.Value = Value("33.19")
    val industrialMachineryInstallation: types.Sector.Value = Value("33.2")
    val industrialMachineryInstallation4: types.Sector.Value = Value("33.20")


    val ElectricityGasSteamAirConditioningSupply: types.Sector.Value = Value("D")
    val ElectricityGasAirConditioningSupply: types.Sector.Value = Value("35")
    val ElectricPowerGenerationAndDistribution	: types.Sector.Value = Value("35.1")
    val ElectricityDistribution  : types.Sector.Value = Value("35.14")
    val NonRenewableElectricityProduction  : types.Sector.Value = Value("35.11")
    val RenewableElectricityProduction: types.Sector.Value = Value("35.12")
    val ElectricityStorage : types.Sector.Value = Value("35.16")
    val ElectricityTrade: types.Sector.Value = Value("35.15")
    val ElectricityTransmission : types.Sector.Value = Value("35.13")
    val GaseousFuelsManufacture: types.Sector.Value = Value("35.2")
    val GaseousFuelDistribution : types.Sector.Value = Value("35.22")
    val GaseousFuelManufacture : types.Sector.Value = Value("35.21")
    val GaseousFuelStorage : types.Sector.Value = Value("35.24")
    val GaseousFuelTrade : types.Sector.Value = Value("35.23")
    val SteamAndAirConditioningSupply	: types.Sector.Value = Value("35.3")
    val SteamAndAirConditioningSupply4: types.Sector.Value = Value("35.30")
    val ElectricPowerAndGasBrokers: types.Sector.Value = Value("35.4")
    val ElectricPowerAndGasBrokers4: types.Sector.Value = Value("35.40")

    val WaterSupplySewereageWasteManagementAndRemediationActivities: types.Sector.Value = Value("E")
    val WaterTreatment: types.Sector.Value = Value("36")
    val WaterTreatment3: types.Sector.Value = Value("36.0")
    val WaterTreatment4: types.Sector.Value = Value("36.00")
    val Sewerage: types.Sector.Value = Value("37")
    val Sewerage3: types.Sector.Value = Value("37.0")
    val Sewerage4: types.Sector.Value = Value("37.00")
    val WasteManagement: types.Sector.Value = Value("38")
    val WasteCollection	: types.Sector.Value = Value("38.1")
    val HazardousWaste: types.Sector.Value = Value("38.12")
    val NonHazardousWaste: types.Sector.Value = Value("38.11")
    val WasteRecovery: types.Sector.Value = Value("38.2")
    val EnergyRecovery: types.Sector.Value = Value("38.22")
    val MaterialsRecovery: types.Sector.Value = Value("38.21")
    val OtherWasteRecovery: types.Sector.Value = Value("38.23")
    val WasteDisposal	: types.Sector.Value = Value("38.3")
    val Incineration: types.Sector.Value = Value("38.31")
    val LandFilling: types.Sector.Value = Value("38.32")
    val OtherWasteDisposal: types.Sector.Value = Value("38.33")
    val WasteManagementRemediation: types.Sector.Value = Value("39")
    val WasteManagementRemediation3: types.Sector.Value = Value("39.0")
    val WasteManagementRemediation4: types.Sector.Value = Value("39.00")

    val Construction: types.Sector.Value = Value("F")
    val buildingsConstruction: types.Sector.Value = Value("41")
    val buildingsConstruction3: types.Sector.Value = Value("41.0")
    val buildingsConstruction4: types.Sector.Value = Value("41.00")

    val CivilEngineering: types.Sector.Value = Value("42")
    val roadAndRailConstruction: types.Sector.Value = Value("42.1")
    val BridgesConstruction: types.Sector.Value = Value("42.13")
    val RailwaysConstruction: types.Sector.Value = Value("42.12")
    val RoadsConstruction: types.Sector.Value = Value("42.11")
    val utilityConstruction: types.Sector.Value = Value("42.2")
    val electricityUtilityConstruction: types.Sector.Value = Value("42.22")
    val fluidsUtilityConstruction: types.Sector.Value = Value("42.21")
    val otherUtilityConstructionProjects: types.Sector.Value = Value("42.9")
    val WaterProjects: types.Sector.Value = Value("42.91")
    val OtherCivilEngineeringProjects: types.Sector.Value = Value("42.99")

    val SpecialisedConstructionActivities: types.Sector.Value = Value("43")
      val DemolitionAndPreparation	: types.Sector.Value = Value("43.1")
        val Demolition: types.Sector.Value = Value("43.11")
        val SitePreparation: types.Sector.Value = Value("43.12")
        val TestDrilling: types.Sector.Value = Value("43.13")
      val ElectricalAndPlumbingInstallation	: types.Sector.Value = Value("43.2")
        val ElectricalInstallation: types.Sector.Value = Value("43.21")
        val insulationInstallation: types.Sector.Value = Value("43.23")
        val PlumbingInstallation: types.Sector.Value = Value("43.22")
        val OtherConstructionInstallation: types.Sector.Value = Value("43.24")
      val BuildingFinishing	: types.Sector.Value = Value("43.3")
        val FloorAndWallCovering: types.Sector.Value = Value("43.33")
        val JoineryInstallation: types.Sector.Value = Value("43.32")
        val PaintingAndGlazing: types.Sector.Value = Value("43.34")
        val Plastering: types.Sector.Value = Value("43.31")
        val OtherBuildingFinishing: types.Sector.Value = Value("43.35")
      val SpecialisedBuildingConstructionActivities: types.Sector.Value = Value("43.4")
        val RoofingActivities: types.Sector.Value = Value("43.41")
        val OtherSpecialisedBuildingConstructionActivities: types.Sector.Value = Value("43.42")
      val SpecialisedCivilConstructionActivities: types.Sector.Value = Value("43.5")
        val SpecialisedCivilConstructionActivities4: types.Sector.Value = Value("43.50")
      val SpecialisedConstructionIntermediationServices: types.Sector.Value = Value("43.6")
        val SpecialisedConstructionIntermediationServices4: types.Sector.Value = Value("43.60")
      val OtherSpecialisedConstruction: types.Sector.Value = Value("43.9")
        val MasonryAndBricklaying: types.Sector.Value = Value("43.91")
        val OtherSpecialisedConstructionActivities: types.Sector.Value = Value("43.99")

    val WholesaleAndRetailTrade: types.Sector.Value = Value("G")
    val Wholesale: types.Sector.Value = Value("46")
    val 	WholesaleContractBasis: types.Sector.Value = Value("46.1")
    val 		AgriculturalWholesaleContractBasis : types.Sector.Value = Value("46.11")
    val 		FoodWholesaleContractBasis: types.Sector.Value = Value("46.17")
    val 		FuelsWholesaleContractBasis: types.Sector.Value = Value("46.12")
    val 		FurnitureWholesaleContractBasis: types.Sector.Value = Value("46.15")
    val 		MachineryWholesaleContractBasis: types.Sector.Value = Value("46.14")
    val 		TextilesWholesaleContractBasis: types.Sector.Value = Value("46.16")
    val 		TimberWholesaleContractBasis : types.Sector.Value = Value("46.13")
    val 		OtherWholesaleContractBasis: types.Sector.Value = Value("46.18")
    val 		 nonSpecialisedWholesaleContractBasis: types.Sector.Value = Value("46.19")
    val 	 agriculturalWholesale: types.Sector.Value = Value("46.2")
    val 		FlowersAndPlants: types.Sector.Value = Value("46.22")
    val 		Grain: types.Sector.Value = Value("46.21")
    val 		leatherWholesale: types.Sector.Value = Value("46.24")
    val 		LiveAnimals: types.Sector.Value = Value("46.23")
    val 	 foodWholesale: types.Sector.Value = Value("46.3")
    val 		BeveragesWholesale: types.Sector.Value = Value("46.34")
    val 		CoffeeAndSpicesWholesale: types.Sector.Value = Value("46.37")
    val 		DairyProductsWholesale: types.Sector.Value = Value("46.33")
    val 		FruitWholesale: types.Sector.Value = Value("46.31")
    val 		MeatWholesale: types.Sector.Value = Value("46.32")
    val 		SugarWholesale: types.Sector.Value = Value("46.36")
    val 		TobaccoProductsWholesale: types.Sector.Value = Value("46.35")
    val 		OtherFoodWholesale	: types.Sector.Value = Value("46.38")
    val 		NonSpecialisedFoodWholesale: types.Sector.Value = Value("46.39")
    val 	WholesaleHouseholdGoods	: types.Sector.Value = Value("46.4")
    val 		ChinaWholesale: types.Sector.Value = Value("46.44")
    val 		ClothingWholesale: types.Sector.Value = Value("46.42")
    val 		ElectricalHouseholdWholesale: types.Sector.Value = Value("46.43")
    val 		HouseholdWholesale: types.Sector.Value = Value("46.47")
    val 		PerfumeWholesale: types.Sector.Value = Value("46.45")
    val 		PharmaceuticalWholesale: types.Sector.Value = Value("46.46")
    val 		TextilesWholesale: types.Sector.Value = Value("46.41")
    val 		WatchesWholesale: types.Sector.Value = Value("46.48")
    val 		OtherHouseholdGoodsWholesale: types.Sector.Value = Value("46.49")
    val 	informationEquipmentWholesale : types.Sector.Value = Value("46.5")
    val 	informationEquipmentWholesale4 : types.Sector.Value = Value("46.50")
    val 	machineryWholesale : types.Sector.Value = Value("46.6")
    val 		AgriculturalMachineryWholesale: types.Sector.Value = Value("46.61")
    val 		MachineToolsWholesale: types.Sector.Value = Value("46.62")
    val 		MiningMachineryWholesale: types.Sector.Value = Value("46.63")
    val 		OtherMachineryWholesale: types.Sector.Value = Value("46.64")
    val 	motorVehiclesWholesale: types.Sector.Value = Value("46.7")
    val 		MotorVehicleWholesale: types.Sector.Value = Value("46.71")
    val 		MotorVehiclePartsWholesale: types.Sector.Value = Value("46.72")
    val 		MotorcyclePartsWholesale: types.Sector.Value = Value("46.73")
    val 	OtherSpecialisedWholesale: types.Sector.Value = Value("46.8")
    val 		ChemicalProductsWholesale: types.Sector.Value = Value("46.85")
    val 		HardwareEquipment : types.Sector.Value = Value("46.84")
    val 		Metals: types.Sector.Value = Value("46.82")
    val 		fuels : types.Sector.Value = Value("46.81")
    val 		Waste : types.Sector.Value = Value("46.87")
    val 		Wood: types.Sector.Value = Value("46.83")
    val 		OtherIntermediateProducts: types.Sector.Value = Value("46.86")
    val 		OtherSpecialisedWholesale4: types.Sector.Value = Value("46.89")
    val 	NonSpecialisedWholesale	: types.Sector.Value = Value("46.9")
    val 		NonSpecialisedWholesaleTrade: types.Sector.Value = Value("46.90")

    val Retail: types.Sector.Value = Value("47")
    val NonSpecialisedRetail: types.Sector.Value = Value("47.1")
    val NonSpecialisedFoodRetail: types.Sector.Value = Value("47.11")
    val OtherNonSpecialisedRetail: types.Sector.Value = Value("47.12")
    val FoodRetail: types.Sector.Value = Value("47.2")
    val BeveragesRetail: types.Sector.Value = Value("47.25")
    val BreadRetail: types.Sector.Value = Value("47.24")
    val FishRetail: types.Sector.Value = Value("47.23")
    val FruitRetail: types.Sector.Value = Value("47.21")
    val MeatRetail: types.Sector.Value = Value("47.22")
    val TobaccoRetail : types.Sector.Value = Value("47.26")
    val OtherFoodRetail: types.Sector.Value = Value("47.27")
    val AutomotiveFuelRetail: types.Sector.Value = Value("47.3")
    val AutomotiveFuelRetail4: types.Sector.Value = Value("47.30")
    val communicationEquipmentRetail: types.Sector.Value = Value("47.4")
    val communicationEquipmentRetail4: types.Sector.Value = Value("47.40")
    val OtherHouseholdEquipmentRetail: types.Sector.Value = Value("47.5")
    val CarpetsRetail: types.Sector.Value = Value("47.53")
    val ElectricalRetail: types.Sector.Value = Value("47.54")
    val HardwareRetail: types.Sector.Value = Value("47.52")
    val TextilesRetail: types.Sector.Value = Value("47.51")
    val FurnitureRetail: types.Sector.Value = Value("47.55")
    val CulturalRetail: types.Sector.Value = Value("47.6")
    val BooksRetail: types.Sector.Value = Value("47.61")
    val GamesRetail: types.Sector.Value = Value("47.64")
    val NewspapersRetail: types.Sector.Value = Value("47.62")
    val SportingEquipmentRetail: types.Sector.Value = Value("47.63")
    val OtherCulturalAndRecreationalGoods: types.Sector.Value = Value("47.69")
    val OtherGoodsRetail: types.Sector.Value = Value("47.7")
    val ClothingRetail: types.Sector.Value = Value("47.71")
    val CosmeticRetail : types.Sector.Value = Value("47.75")
    val FlowersRetail: types.Sector.Value = Value("47.76")
    val FootwearRetail : types.Sector.Value = Value("47.72")
    val MedicalRetail : types.Sector.Value = Value("47.74")
    val PharmaceuticalRetail: types.Sector.Value = Value("47.73")
    val WatchesRetail: types.Sector.Value = Value("47.77")
    val OtherNewGoodsRetail: types.Sector.Value = Value("47.78")
    val SecondHandGoods: types.Sector.Value = Value("47.79")
    val MotorVehiclesAndMotorcyclesRetail: types.Sector.Value = Value("47.8")
    val MotorVehiclesRetail: types.Sector.Value = Value("47.81")
    val MotorVehiclesPartsRetail: types.Sector.Value = Value("47.82")
    val MotorcyclesRetail: types.Sector.Value = Value("47.83")
    val RetailIntermediationServices: types.Sector.Value = Value("47.9")
    val NonSpecialisedRetailIntermediation: types.Sector.Value = Value("47.91")
    val SpecialisedRetailIntermediation: types.Sector.Value = Value("47.92")
    val TransportationAndStorage : types.Sector.Value = Value("H")
    val LandTransport : types.Sector.Value = Value("49")
    val PassengerRailTransport	: types.Sector.Value = Value("49.1")
    val PassengerHeavyRailTransport: types.Sector.Value = Value("49.11")
    val OtherPassengerRailTransport: types.Sector.Value = Value("49.12")
    val FreightRailTransport: types.Sector.Value = Value("49.2")
    val FreightRailTransport4: types.Sector.Value = Value("49.20")
    val OtherPassengerLandTransport	: types.Sector.Value = Value("49.3")
    val NonScheduledPassengerRoadTransport: types.Sector.Value = Value("49.32")
    val OnDemandPassengerRoadTransport: types.Sector.Value = Value("49.33")
    val cablewaysPassengerTransport: types.Sector.Value = Value("49.34")
    val ScheduledPassengerRoadTransport: types.Sector.Value = Value("49.31")
    val OtherLandTransport: types.Sector.Value = Value("49.39")
    val FreightRoadTransport: types.Sector.Value = Value("49.4")
    val FreightRoadTransport4: types.Sector.Value = Value("49.41")
    val RemovalServices: types.Sector.Value = Value("49.42")
    val pipelineTransport: types.Sector.Value = Value("49.5")
    val pipelineTransport4 : types.Sector.Value = Value("49.50")
    val  WaterTransport: types.Sector.Value = Value("50")
    val  coastalPassengerWaterTransport: types.Sector.Value = Value("50.1")
    val  coastalPassengerWaterTransport4: types.Sector.Value = Value("50.10")
    val  coastalFreightWaterTransport: types.Sector.Value = Value("50.2")
    val  coastalFreightWaterTransport4: types.Sector.Value = Value("50.20")
    val  InlandPassengerWaterTransport: types.Sector.Value = Value("50.3")
    val  InlandPassengerWaterTransport4: types.Sector.Value = Value("50.30")
    val  InlandFreightWaterTransport: types.Sector.Value = Value("50.4")
    val  InlandFreightWaterTransport4: types.Sector.Value = Value("50.40")

    val  AirTransport: types.Sector.Value = Value("51")
    val  PassengerAirTransport	: types.Sector.Value = Value("51.1")
    val  PassengerAirTransport4: types.Sector.Value = Value("51.10")
    val  FreightAndSpaceAirTransport: types.Sector.Value = Value("51.2")
    val  FreightAirTransport: types.Sector.Value = Value("51.21")
    val  SpaceTransport: types.Sector.Value = Value("51.22")
    val  WarehousingStorageTransportSupportActivities: types.Sector.Value = Value("52")
    val  	WarehousingStorage	: types.Sector.Value = Value("52.1")
    val  		WarehousingStorage4: types.Sector.Value = Value("52.10")
    val  	transportSupportActivities: types.Sector.Value = Value("52.2")
    val  		CargoHandling: types.Sector.Value = Value("52.24")
    val  		LogisticsServiceActivities: types.Sector.Value = Value("52.25")
    val  		airTransportServiceActivities : types.Sector.Value = Value("52.23")
    val  		landTransportServiceActivities: types.Sector.Value = Value("52.21")
    val  		 waterTransportServiceActivities: types.Sector.Value = Value("52.22")
    val  		OtherTransportSupportActivities: types.Sector.Value = Value("52.26")
    val  	transportIntermediationServiceActivities	: types.Sector.Value = Value("52.3")
    val  	freightTransportIntermediationServiceActivities: types.Sector.Value = Value("52.31")
    val  	passengerTransportIntermediationServiceActivities: types.Sector.Value = Value("52.32")
    val PostalAndCourierActivities: types.Sector.Value = Value("53")
    val PostalActivities: types.Sector.Value = Value("53.1")
    val PostalActivities4: types.Sector.Value = Value("53.10")
    val OtherPostalActivities: types.Sector.Value = Value("53.2")
    val OtherPostalActivities4: types.Sector.Value = Value("53.20")
    val PostalIntermediationActivities	: types.Sector.Value = Value("53.3")
    val PostalIntermediationActivities4: types.Sector.Value = Value("53.30")

    val AccommodationAndFoodServiceActivities: types.Sector.Value = Value("I")
    val Accommodation: types.Sector.Value = Value("55")
    val Hotels: types.Sector.Value = Value("55.1")
    val Hotels4: types.Sector.Value = Value("55.10")
    val HolidayAccommodation: types.Sector.Value = Value("55.2")
    val HolidayAccommodation4: types.Sector.Value = Value("55.20")
    val CampingGrounds: types.Sector.Value = Value("55.3")
    val CampingGrounds4: types.Sector.Value = Value("55.30")
    val AccommodationIntermediationServiceActivities: types.Sector.Value = Value("55.4")
    val AccommodationIntermediationServiceActivities4: types.Sector.Value = Value("55.40")
    val OtherAccommodation	: types.Sector.Value = Value("55.9")
    val OtherAccommodation4: types.Sector.Value = Value("55.90")

    val FoodBeverageServiceActivities: types.Sector.Value = Value("56")
    val Restaurants: types.Sector.Value = Value("56.1")
    val Restaurants4: types.Sector.Value = Value("56.11")
    val MobileFoodServices: types.Sector.Value = Value("56.12")
    val EventAndContractCatering: types.Sector.Value = Value("56.2")
    val EventCatering: types.Sector.Value = Value("56.21")
    val ContractCatering: types.Sector.Value = Value("56.22")
    val BeverageServing: types.Sector.Value = Value("56.3")
    val contractActivities: types.Sector.Value = Value("56.30")
    val FoodBeverageServiceIntermediationActivities	: types.Sector.Value = Value("56.4")
    val FoodBeverageServiceIntermediationActivities4: types.Sector.Value = Value("56.40")

    val PublishingBroadcastingAndContentProductionAndDistributionActivities: types.Sector.Value = Value("J")
    val Publishing: types.Sector.Value = Value("58")
    val PublishingBooksNewspapers: types.Sector.Value = Value("58.1")
    val Books: types.Sector.Value = Value("58.11")
    val JournalsPeriodicals: types.Sector.Value = Value("58.13")
    val Newspapers: types.Sector.Value = Value("58.12")
    val OtherPublishing: types.Sector.Value = Value("58.19")
    val SoftwarePublishing: types.Sector.Value = Value("58.2")
    val VideoGames: types.Sector.Value = Value("58.21")
    val OtherSoftware: types.Sector.Value = Value("58.29")

    val FilmVideoSoundPublishing: types.Sector.Value = Value("59")
    val FilmVideoActivities: types.Sector.Value = Value("59.1")
    val VideoProductionDistribution: types.Sector.Value = Value("59.13")
    val VideoPostProduction: types.Sector.Value = Value("59.12")
    val VideoProduction: types.Sector.Value = Value("59.11")
    val Projection: types.Sector.Value = Value("59.14")
    val SoundRecordingAndMusicPublishing: types.Sector.Value = Value("59.2")
    val SoundRecordingAndMusicPublishingActivities: types.Sector.Value = Value("59.20")

    val ProgrammingBroadcastingNewsActivities: types.Sector.Value = Value("60")
    val RadioBroadcasting: types.Sector.Value = Value("60.1")
    val RadioBroadcasting4: types.Sector.Value = Value("60.10")
    val ProgrammingBroadcastingVideoDistribution: types.Sector.Value = Value("60.2")
    val ProgrammingBroadcastingVideoDistribution4: types.Sector.Value = Value("60.20")
    val NewsAgency: types.Sector.Value = Value("60.3")
    val NewsAgencyActivities: types.Sector.Value = Value("60.31")
    val OtherContentDistributionActivities: types.Sector.Value = Value("60.39")

    val TelecommunicationComputerProgrammingConsultingComputingInfrastructureAndOtherInformationSericeActivities: types.Sector.Value = Value("K")
    val Telecommunication: types.Sector.Value = Value("61")
    val telecommunicationActivities: types.Sector.Value = Value("61.1")
    val telecommunicationActivities4: types.Sector.Value = Value("61.10")
    val TelecommunicationResellingIntermediation: types.Sector.Value = Value("61.2")
    val TelecommunicationResellingIntermediation4: types.Sector.Value = Value("61.20")
    val OtherTelecommunicationActivities: types.Sector.Value = Value("61.9")
    val OtherTelecommunicationActivities4: types.Sector.Value = Value("61.90")

    val ComputerProgrammingAndFacilitiesActivities: types.Sector.Value = Value("62")
    val ComputerProgrammingActivities3: types.Sector.Value = Value("62.1")
    val ComputerProgrammingActivities4: types.Sector.Value = Value("62.10")
    val ComputerFacilitiesManagement: types.Sector.Value = Value("62.2")
    val ComputerFacilitiesManagement4: types.Sector.Value = Value("62.20")
    val OtherComputerServiceActivities: types.Sector.Value = Value("62.9")
    val OtherComputerServiceActivities4: types.Sector.Value = Value("62.90")

    val ComputingInfrastructureActivities: types.Sector.Value = Value("63")
    val ComputingInfrastructureActivities3: types.Sector.Value = Value("63.1")
    val ComputingInfrastructureActivities4: types.Sector.Value = Value("63.10")
    val WebSearchActivities: types.Sector.Value = Value("63.9")
    val WebSearchActivities3: types.Sector.Value = Value("63.91")
    val WebSearchActivities4: types.Sector.Value = Value("63.92")

    val FinancialAndInsuranceActivities: types.Sector.Value = Value("L")
    val FinancialServices: types.Sector.Value = Value("64")
    val MonetaryIntermediation: types.Sector.Value = Value("64.1")
    val CentralBanking: types.Sector.Value = Value("64.11")
    val OtherMonetaryIntermediation: types.Sector.Value = Value("64.19")
    val HoldingCompaniesAndFinancingConduits: types.Sector.Value = Value("64.2")
    val FinancingConduits: types.Sector.Value = Value("64.22")
    val HoldingCompanies: types.Sector.Value = Value("64.21")
    val TrustsAndSimilar: types.Sector.Value = Value("64.3")
    val MoneyMarketInvestmentsFunds: types.Sector.Value = Value("64.31")
    val Trusts: types.Sector.Value = Value("64.32")
    val OtherFinancialServices: types.Sector.Value = Value("64.9")
    val FinancialLeasing: types.Sector.Value = Value("64.91")
    val OtherCreditGranting: types.Sector.Value = Value("64.92")
    val OtherFinancialServices4: types.Sector.Value = Value("64.99")

    val InsuranceReinsurancePensionFunding: types.Sector.Value = Value("65")
    val Insurance: types.Sector.Value = Value("65.1")
    val LifeInsurance: types.Sector.Value = Value("65.11")
    val NonLifeInsurance: types.Sector.Value = Value("65.12")
    val Reinsurance: types.Sector.Value = Value("65.2")
    val Reinsurance4: types.Sector.Value = Value("65.20")
    val PensionFunding: types.Sector.Value = Value("65.3")
    val PensionFunding4: types.Sector.Value = Value("65.30")

    val auxiliaryActivities :types.Sector.Value = Value("66")
    val nonInsuranceAuxiliaryActivities	: types.Sector.Value = Value("66.1")
    val financialMarketsAdministration : types.Sector.Value = Value("66.11")
    val SecurityContractsBrokerage: types.Sector.Value = Value("66.12")
    val nonInsuranceOtherAuxiliaryActivities: types.Sector.Value = Value("66.19")
    val pensionFundingAuxiliaryActivities: types.Sector.Value = Value("66.2")
    val brokerActivities : types.Sector.Value = Value("66.22")
    val RiskEvaluation: types.Sector.Value = Value("66.21")
    val OtherAuxiliaryActivities: types.Sector.Value = Value("66.29")
    val FundManagement	: types.Sector.Value = Value("66.3")
    val FundManagementActivities: types.Sector.Value = Value("66.30")

    val RealEstate: types.Sector.Value = Value("M")
    val RealEstateActivities: types.Sector.Value = Value("68")
    val RealEstateActivitiesOwnProperty: types.Sector.Value = Value("68.1")
    val BuyingSellingRealEstateActivitiesOwnProperty: types.Sector.Value = Value("68.11")
    val DevelopmentRealEstateActivitiesOwnProperty: types.Sector.Value = Value("68.12")
    val realEstateRental: types.Sector.Value = Value("68.2")
    val realEstateRental4: types.Sector.Value = Value("68.20")
    val realEstateRentalContracts: types.Sector.Value = Value("68.3")
    val realEstateIntermediationActivities: types.Sector.Value = Value("68.31")
    val OtherRealEstateActivities: types.Sector.Value = Value("68.32")

    val ProfessionalScientificAndTechnicalActivities: types.Sector.Value = Value("N")
    val LegalAndAccounting: types.Sector.Value = Value("69")
    val LegalActivities	: types.Sector.Value = Value("69.1")
    val LegalActivities4: types.Sector.Value = Value("69.10")
    val Accounting: types.Sector.Value = Value("69.2")
    val AccountingTaxConsultancy: types.Sector.Value = Value("69.20")

    val HeadOfficesAndManagementConsultancy	: types.Sector.Value = Value("70")
    val HeadOfficesActivities: types.Sector.Value = Value("70.1")
    val HeadOfficesActivities4: types.Sector.Value = Value("70.10")
    val ManagementConsultancyActivities	: types.Sector.Value = Value("70.2")
    val ManagementConsultancyActivities4: types.Sector.Value = Value("70.20")

    val ArchitecturalAndTechnical: types.Sector.Value = Value("71")
    val ArchitecturalAndTechnicalActivities: types.Sector.Value = Value("71.1")
    val ArchitecturalActivities: types.Sector.Value = Value("71.11")
    val EngineeringActivities: types.Sector.Value = Value("71.12")
    val TechnicalTesting: types.Sector.Value = Value("71.2")
    val TechnicalTesting4: types.Sector.Value = Value("71.20")

    val ScientificResearchAndDevelopment: types.Sector.Value = Value("72")
    val NaturalScientificResearchAndDevelopment: types.Sector.Value = Value("72.1")
    val NaturalScientificResearchAndDevelopment4: types.Sector.Value = Value("72.10")
    val SocialScientificResearchAndDevelopment: types.Sector.Value = Value("72.2")
    val SocialScientificResearchAndDevelopment4: types.Sector.Value = Value("72.20")

    val AdvertisingMarketResearch: types.Sector.Value = Value("73")
    val Advertising: types.Sector.Value = Value("73.1")
    val AdvertisingActivities: types.Sector.Value = Value("73.11")
    val MediaRepresentation: types.Sector.Value = Value("73.12")
    val MarketResearch: types.Sector.Value = Value("73.2")
    val MarketResearch4: types.Sector.Value = Value("73.20")
    val PublicRelations: types.Sector.Value = Value("73.3")
    val PublicRelations4: types.Sector.Value = Value("73.30")

    val otherProfessionalScientific: types.Sector.Value = Value("74")
    val SpecialisedDesignActivities	: types.Sector.Value = Value("74.1")
    val GraphicDesignActivities: types.Sector.Value = Value("74.12")
    val IndustrialDesignActivities: types.Sector.Value = Value("74.11")
    val InteriorDesignActivities: types.Sector.Value = Value("74.13")
    val OtherDesignActivities: types.Sector.Value = Value("74.14")
    val Photography	: types.Sector.Value = Value("74.2")
    val PhotographicActivities: types.Sector.Value = Value("74.20")
    val TranslationActivities: types.Sector.Value = Value("74.3")
    val TranslationActivities4: types.Sector.Value = Value("74.30")
    val otherProfessionalScientificActivities: types.Sector.Value = Value("74.9")
    val PatentBrokeringActivities: types.Sector.Value = Value("74.91")
    val otherProfessionalScientificActivities4: types.Sector.Value = Value("74.99")

    val VeterinaryActivities: types.Sector.Value = Value("75")
    val VeterinaryActivities3: types.Sector.Value = Value("75.0")
    val VeterinaryActivities4: types.Sector.Value = Value("75.00")

    val AdministrativeAndSupportServiceActivities: types.Sector.Value = Value("O")
    val RentalAndLeasing: types.Sector.Value = Value("77")
    val MotorVehiclesRental: types.Sector.Value = Value("77.1")
    val CarRental: types.Sector.Value = Value("77.11")
    val TruckRental: types.Sector.Value = Value("77.12")
    val PersonalRental	: types.Sector.Value = Value("77.2")
    val RecreationalRental: types.Sector.Value = Value("77.21")
    val OtherPersonalRental: types.Sector.Value = Value("77.22")
    val OtherMachineryRental: types.Sector.Value = Value("77.3")
    val AgriculturalMachineryRental: types.Sector.Value = Value("77.31")
    val AirTransportRental: types.Sector.Value = Value("77.35")
    val ConstructionMachineryRental: types.Sector.Value = Value("77.32")
    val OfficeMachineryRental: types.Sector.Value = Value("77.33")
    val WaterTransportRental: types.Sector.Value = Value("77.34")
    val OtherMachineryRental4: types.Sector.Value = Value("77.39")
    val IntellectualProperty: types.Sector.Value = Value("77.4")
    val LeasingIntellectualProperty: types.Sector.Value = Value("77.40")
	val TangibleGoodsRentalIntermediation: types.Sector.Value = Value("77.5")
    val CarsMotorhomesTrailers: types.Sector.Value = Value("77.51")
    val  OtherTangibleGoodsRental: types.Sector.Value = Value("77.52")

    val Employment: types.Sector.Value = Value("78")
    val EmploymentPlacementActivities: types.Sector.Value = Value("78.1")
    val EmploymentPlacementActivities4: types.Sector.Value = Value("78.10")
    val TempEmploymentPlacementActivities: types.Sector.Value = Value("78.2")
    val TempEmploymentPlacementActivities4: types.Sector.Value = Value("78.20")

    val TravelAgencyAndReservation: types.Sector.Value = Value("79")
    val TravelAgency: types.Sector.Value = Value("79.1")
    val TourOperator: types.Sector.Value = Value("79.12")
    val TravelAgencyActivities: types.Sector.Value = Value("79.11")
    val OtherReservationServices: types.Sector.Value = Value("79.9")
    val OtherReservationServices4: types.Sector.Value = Value("79.90")

    val InvestigationAndSecurity: types.Sector.Value = Value("80")
    val InvestigationAndSecurityActivities: types.Sector.Value = Value("80.0")
    val PrivateInvestigationAndSecurityActivities: types.Sector.Value = Value("80.01")
    val OtherInvestigationAndSecurityActivities: types.Sector.Value = Value("80.09")

    val buildingsAndLandscapingServices:types.Sector.Value = Value("81")
    val CombinedFacilitiesSupport: types.Sector.Value = Value("81.1")
    val CombinedFacilitiesSupport4: types.Sector.Value = Value("81.10")
    val Cleaning: types.Sector.Value = Value("81.2")
    val GeneralCleaning	: types.Sector.Value = Value("81.21")
    val OtherBuildingCleaning: types.Sector.Value = Value("81.22")
    val OtherCleaning: types.Sector.Value = Value("81.23")
    val Landscaping: types.Sector.Value = Value("81.3")
    val LandscapeServiceActivities	: types.Sector.Value = Value("81.30")

    val OfficeAdministrativeSupport: types.Sector.Value = Value("82")
    val OfficeAdministrative: types.Sector.Value = Value("82.1")
    val OfficeAdministrativeActivities4: types.Sector.Value = Value("82.10")
    val CallCentres: types.Sector.Value = Value("82.2")
    val CallCentresActivities: types.Sector.Value = Value("82.20")
    val conventionsOrganisation: types.Sector.Value = Value("82.3")
    val conventionsOrganisation4: types.Sector.Value = Value("82.30")
    val businessSupportIntermediation: types.Sector.Value = Value("82.4")
    val businessSupportIntermediation4: types.Sector.Value = Value("82.40")
    val OtherBusinessSupportIntermediationService: types.Sector.Value = Value("82.9")
    val CollectionAgencies: types.Sector.Value = Value("82.91")
    val PackagingActivities: types.Sector.Value = Value("82.92")
    val OtherBusinessSupport: types.Sector.Value = Value("82.99")

    val PublicAdministrationAndDefenceCompulsorySocialSecurity: types.Sector.Value = Value("P")
    val PublicAdministrationSocialSecurity: types.Sector.Value = Value("84")
    val administrationGeneral: types.Sector.Value = Value("84.1")
    val generalPublicAdmin: types.Sector.Value = Value("84.11")
    val healthEducationRegulation: types.Sector.Value = Value("84.12")
    val businessRegulation: types.Sector.Value = Value("84.13")
    val communityServices: types.Sector.Value = Value("84.2")
    val defence: types.Sector.Value = Value("84.22")
    val fireServiceActivities: types.Sector.Value = Value("84.25")
    val foreignAffairs: types.Sector.Value = Value("84.21")
    val judicialActivities: types.Sector.Value = Value("84.23")
    val publicSafety: types.Sector.Value = Value("84.24")
    val compulsorySocialSecurity	: types.Sector.Value = Value("84.3")
    val compulsorySocialSecurity4: types.Sector.Value = Value("84.30")

    val education: types.Sector.Value = Value("Q")
    val education2: types.Sector.Value = Value("85")
    val prePrimaryEducation	: types.Sector.Value = Value("85.1")
    val prePrimaryEducation4: types.Sector.Value = Value("85.10")
    val primaryEducation: types.Sector.Value = Value("85.2")
    val primaryEducation4: types.Sector.Value = Value("85.20")
    val secondaryEducation: types.Sector.Value = Value("85.3")
    val generalSecondaryEducation: types.Sector.Value = Value("85.31")
    val vocationalSecondaryEducation: types.Sector.Value = Value("85.32")
    val postSecondaryEducationNonTertiary: types.Sector.Value = Value("85.33")
    val tertiaryEducation: types.Sector.Value = Value("85.4")
    val tertiaryEducation4: types.Sector.Value = Value("85.40")
    val otherEducation: types.Sector.Value = Value("85.5")
    val culturalEducation: types.Sector.Value = Value("85.52")
    val drivingSchool: types.Sector.Value = Value("85.53")
    val sportsRecreationEducation: types.Sector.Value = Value("85.51")
    val otherEducationNEC: types.Sector.Value = Value("85.59")
    val educationalSupport: types.Sector.Value = Value("85.6")
    val educationalSupportIntermediation : types.Sector.Value = Value("85.61")
    val otherEducationalSupport: types.Sector.Value = Value("85.69")

    val HumanHealthAndSocialWorkActivities: types.Sector.Value = Value("R")
    val HumanHealthActivities: types.Sector.Value = Value("86")
    val hospital : types.Sector.Value = Value("86.1")
    val HospitalActivities: types.Sector.Value = Value("86.10")
    val medicalDental : types.Sector.Value = Value("86.2")
    val dental: types.Sector.Value = Value("86.23")
    val generalPractice: types.Sector.Value = Value("86.21")
    val specialists: types.Sector.Value = Value("86.22")
    val otherHumanHealth: types.Sector.Value = Value("86.9")
    val psychologists: types.Sector.Value = Value("86.93")
    val diagnosticImaging: types.Sector.Value = Value("86.91")
    val nursingMidwifery: types.Sector.Value = Value("86.94")
    val ambulance: types.Sector.Value = Value("86.92")
    val physiotherapy: types.Sector.Value = Value("86.95")
    val traditionalMedicine: types.Sector.Value = Value("86.96")
    val humanHealthActivitiesIntermediationServices : types.Sector.Value = Value("86.97")
    val OtherHumanHealthActivities4: types.Sector.Value = Value("86.99")

    val ResidentialCareActivities: types.Sector.Value = Value("87")
    val ResidentialNursing: types.Sector.Value = Value("87.1")
    val ResidentialNursing4: types.Sector.Value = Value("87.10")
    val ResidentialCareActivitiesMentalIllness: types.Sector.Value = Value("87.2")
    val ResidentialCareActivitiesMentalIllness4: types.Sector.Value = Value("87.20")
    val DisabledResidentialCareActivitiesMentalIllness: types.Sector.Value = Value("87.3")
    val DisabledResidentialCareActivitiesMentalIllness4: types.Sector.Value = Value("87.30")
    val OtherResidentialCare: types.Sector.Value = Value("87.9")
    val otherResidentialCareIntermediation: types.Sector.Value = Value("87.91")
    val otherResidentialCare4: types.Sector.Value = Value("87.99")

    val otherSocialWork: types.Sector.Value = Value("88")
    val socialWorkDisabilities: types.Sector.Value = Value("88.1")
    val socialWorkDisabilities4: types.Sector.Value = Value("88.10")
    val otherSocialWorkWithoutAccommodation: types.Sector.Value = Value("88.9")
    val childDayCare: types.Sector.Value = Value("88.91")
    val otherSocialWorkNEC: types.Sector.Value = Value("88.99")

    val ArtsSportsAndRecreation: types.Sector.Value = Value("S")
    val ArtsCreation: types.Sector.Value = Value("90")
    val ArtCreation: types.Sector.Value = Value("90.1")
    val LiteraryCreation: types.Sector.Value = Value("90.11")
    val VisualArtsCreation: types.Sector.Value = Value("90.12")
    val OtherArtsCreation: types.Sector.Value = Value("90.13")
    val PerformingArts: types.Sector.Value = Value("90.2")
    val PerformingArtsActivities: types.Sector.Value = Value("90.20")
    val PerformingArtsSupport: types.Sector.Value = Value("90.3")
    val artsFacilitiesOperation: types.Sector.Value = Value("90.31")
    val OtherPerformingArtsSupport: types.Sector.Value = Value("90.39")

    val LibrariesArchivesMuseums: types.Sector.Value = Value("91")
    val LibrariesAndArchives	: types.Sector.Value = Value("91.1")
    val Archives: types.Sector.Value = Value("91.12")
    val Libraries: types.Sector.Value = Value("91.11")
    val MuseumsAndHistorical: types.Sector.Value = Value("91.2")
    val HistoricalSites: types.Sector.Value = Value("91.22")
    val Museums: types.Sector.Value = Value("91.21")
    val ConservationRestoration	: types.Sector.Value = Value("91.3")
    val ConservationRestoration4: types.Sector.Value = Value("91.30")
    val BotanicalGardensAndNatureReserves: types.Sector.Value = Value("91.4")
    val BotanicalGardens: types.Sector.Value = Value("91.41")
    val NatureReserves: types.Sector.Value = Value("91.42")

    val Gambling: types.Sector.Value = Value("92")
    val GamblingActivities: types.Sector.Value = Value("92.0")
    val GamblingActivities4: types.Sector.Value = Value("92.00")

    val SportsAndRecreation: types.Sector.Value = Value("93")
    val Sports: types.Sector.Value = Value("93.1")
    val fitnessCentreActivities: types.Sector.Value = Value("93.13")
    val sportsClubsActivities : types.Sector.Value = Value("93.12")
    val sportsFacilitiesOperation : types.Sector.Value = Value("93.11")
    val OtherSportsActivities: types.Sector.Value = Value("93.19")
    val AmusementAndRecreation	: types.Sector.Value = Value("93.2")
    val AmusementParks: types.Sector.Value = Value("93.21")
    val OtherRecreationActivities: types.Sector.Value = Value("93.29")

    val OtherServiceActivities: types.Sector.Value = Value("T")
    val membershipOrganisationActivities: types.Sector.Value = Value("94")
    val BusinessProfessionalMembershipOrganisations: types.Sector.Value = Value("94.1")
    val BusinessMembershipOrganisations: types.Sector.Value = Value("94.11")
    val ProfessionalMembershipOrganisations: types.Sector.Value = Value("94.12")
    val TradeUnions: types.Sector.Value = Value("94.2")
    val TradeUnionsActivities: types.Sector.Value = Value("94.20")
    val OtherMembershipOrganisations: types.Sector.Value = Value("94.9")
    val PoliticalOrganisations: types.Sector.Value = Value("94.92")
    val ReligiousOrganisations: types.Sector.Value = Value("94.91")
    val AnotherTypeMembershipOrganisation: types.Sector.Value = Value("94.99")

    val computerAndMotorcycleMaintenance: types.Sector.Value = Value("95")
    val ComputerEquipment: types.Sector.Value = Value("95.1")
    val ComputersEquipmentMaintenance: types.Sector.Value = Value("95.10")
    val PersonalGoods: types.Sector.Value = Value("95.2")
    val ConsumerElectronicMaintenances: types.Sector.Value = Value("95.21")
    val FootwearAndLeatherGoods: types.Sector.Value = Value("95.23")
    val FurnitureAndFurnishings: types.Sector.Value = Value("95.24")
    val HouseholdAppliancesAndGardenEquipment: types.Sector.Value = Value("95.22")
    val WatchesAndJewellery: types.Sector.Value = Value("95.25")
    val otherHouseholdGoods: types.Sector.Value = Value("95.29")
    val MotorVehiclesAndMotorcycles: types.Sector.Value = Value("95.3")
    val MotorVehiclesRepair: types.Sector.Value = Value("95.31")
    val MotorcycleRepair: types.Sector.Value = Value("95.32")
    val computerAndMotorcycleMaintenanceIntermediationServiceActivities	: types.Sector.Value = Value("95.4")
    val computerAndMotorcycleMaintenanceIntermediationServiceActivities4: types.Sector.Value = Value("95.40")

    val PersonalServices: types.Sector.Value = Value("96")
    val cleaningTextileProducts	: types.Sector.Value = Value("96.1")
    val cleaningTextileProducts4: types.Sector.Value = Value("96.10")
    val beautyTreatment: types.Sector.Value = Value("96.2")
    val beautyTreatments: types.Sector.Value = Value("96.22")
    val spaActivities: types.Sector.Value = Value("96.23")
    val Hairdressing: types.Sector.Value = Value("96.21")
    val FuneralActivities: types.Sector.Value = Value("96.3")
    val FuneralActivities4: types.Sector.Value = Value("96.30")
    val personalServicesIntermediation	: types.Sector.Value = Value("96.4")
    val personalServicesIntermediation4: types.Sector.Value = Value("96.40")
    val otherPersonalServices: types.Sector.Value = Value("96.9")
    val DomesticPersonalServices: types.Sector.Value = Value("96.91")
    val AnyOtherPersonalServiceActivities: types.Sector.Value = Value("96.99")

   val activitiesOfHouseholdsAsEmployers: types.Sector.Value = Value("U")
   val householdsActivitiesOfDomesticPersonnel: types.Sector.Value = Value("97")
   val householdsActivitiesOfDomesticPersonnel3: types.Sector.Value = Value("97.0")
   val householdsActivitiesOfDomesticPersonnel4: types.Sector.Value = Value("97.00")
   val undifferentiatedGoodsAndServiceActivities: types.Sector.Value = Value("98")
   val undifferentiatedGoods: types.Sector.Value = Value("98.1")
   val undifferentiatedGoods4: types.Sector.Value = Value("98.10")
   val undifferentiatedServices: types.Sector.Value = Value("98.2")
   val undifferentiatedServices4: types.Sector.Value = Value("98.20")

   val activitiesOfExtraterritorialOrganisationsAndBodies: types.Sector.Value = Value("V")
   val extraterritorialOrganisationsActivities: types.Sector.Value = Value("99")
   val extraterritorialOrganisationsActivities3: types.Sector.Value = Value("99.0")
   val extraterritorialOrganisationsActivities4: types.Sector.Value = Value("99.00")

    implicit val format: Format[Sector] = Json.formatEnum(Sector)
  }
  object UndertakingStatus extends Enumeration {
    type UndertakingStatus = Value
    val active: types.UndertakingStatus.Value = Value(0)
    val suspendedAutomated: types.UndertakingStatus.Value = Value(1)
    val suspendedManual: types.UndertakingStatus.Value = Value(5)
    val suspendedUndertaking: types.UndertakingStatus.Value = Value(8)
    val inactive: types.UndertakingStatus.Value = Value(9)
    implicit val format: Format[UndertakingStatus] = Json.formatEnum(UndertakingStatus)
  }

  type SubsidyRef = String @@ SubsidyRef.Tag
  object SubsidyRef
      extends RegexValidatedString(
        "^[A-Za-z0-9]{1,10}$" // n.b. no longer exact match for spec which accepts n of any char
      )

  type EisSubsidyAmendmentType = String @@ EisSubsidyAmendmentType.Tag
  object EisSubsidyAmendmentType
      extends RegexValidatedString(
        regex = "1|2|3"
      )

  object AmendmentType extends Enumeration {
    type AmendmentType = Value

    val add: types.AmendmentType.Value = Value("1")
    val amend: types.AmendmentType.Value = Value("2")
    val delete: types.AmendmentType.Value = Value("3")

    implicit val format: Format[AmendmentType] = Json.formatEnum(AmendmentType)

  }

  type ErrorMessage = String @@ ErrorMessage.Tag
  object ErrorMessage
      extends RegexValidatedString(
        """.{1,255}"""
      )

  object EmailStatus extends Enumeration {
    type EmailStatus = Value
    val Unverified: types.EmailStatus.Value = Value("unverified")
    val New: types.EmailStatus.Value = Value("new")
    val Amend: types.EmailStatus.Value = Value("amend")
    val BecomeLead: types.EmailStatus.Value = Value("become-lead")
    val CYA: types.EmailStatus.Value = Value("cya")

    implicit val format: Format[EmailStatus] = Json.formatEnum(EmailStatus)

    implicit object Binder extends PathBindable[EmailStatus] {

      override def bind(key: String, value: String): Either[String, EmailStatus] =
        Try(EmailStatus.withName(value)).toOption
          .map(Right(_))
          .getOrElse(Left("Cannot parse parameter '" + key + "' as EmailStatus"))

      override def unbind(key: String, value: EmailStatus): String = value.toString

    }

    implicit val queryStringBindable: QueryStringBindable[EmailStatus] =
      new QueryStringBindable[EmailStatus] {
        override def bind(
          key: String,
          params: Map[String, Seq[String]]
        ): Option[Either[String, EmailStatus]] =
          params.get(key).collect { case Seq(s) =>
            EmailStatus.values.find(_.toString == s).toRight("invalid sort field parameter")
          }

        override def unbind(key: String, value: EmailStatus): String =
          implicitly[QueryStringBindable[String]].unbind(key, value.toString)
      }
  }

  object VerifiedStatus extends Enumeration {
    type VerifiedStatus = Value
    val Verified: types.VerifiedStatus.Value = Value("verified")

    implicit val format: Format[VerifiedStatus] = Json.formatEnum(VerifiedStatus)
  }

}
